#include <TClonesArray.h>
#include <TTree.h>
#include "SharedHandle.h"
#include <vector>

using namespace std;

Long64_t m_entry_number;

SharedHandle<Int_t> event("event", &m_entry_number);
SharedHandle<Int_t> lumis("lumis", &m_entry_number);
SharedHandle<Int_t> run("run", &m_entry_number);
SharedHandle<Int_t> bx("bx", &m_entry_number);
SharedHandle<TClonesArray*> sc_p4("sc_p4", &m_entry_number);
SharedHandle<TClonesArray*> sc_xyz("sc_xyz", &m_entry_number);
SharedHandle<Int_t> sc_n("sc_n", &m_entry_number);
SharedHandle<Float_t*> sc_sphi("sc_sphi", &m_entry_number, 200);
SharedHandle<Float_t*> sc_seta("sc_seta", &m_entry_number, 200);
SharedHandle<Float_t*> sc_raw("sc_raw", &m_entry_number, 200);
SharedHandle<Float_t*> sc_pre("sc_pre", &m_entry_number, 200);
SharedHandle<Int_t*> sc_bcseedind("sc_bcseedind", &m_entry_number, 200);
SharedHandle<Int_t*> sc_nbc("sc_nbc", &m_entry_number, 200);
SharedHandle<Int_t> ecalhit_n("ecalhit_n", &m_entry_number);
SharedHandle<Int_t*> ecalhit_detid("ecalhit_detid", &m_entry_number, 10000);
SharedHandle<TClonesArray*> ecalhit_p4("ecalhit_p4", &m_entry_number);
SharedHandle<Int_t> bc_n("bc_n", &m_entry_number);
SharedHandle<TClonesArray*> bc_p4("bc_p4", &m_entry_number);
SharedHandle<Int_t> tk_n("tk_n", &m_entry_number);
SharedHandle<TClonesArray*> tk_p4("tk_p4", &m_entry_number);
SharedHandle<TClonesArray*> tk_vtx_pos("tk_vtx_pos", &m_entry_number);
SharedHandle<Int_t*> tk_nhits("tk_nhits", &m_entry_number, 10000);
SharedHandle<Int_t*> tk_nlosthit("tk_nlosthit", &m_entry_number, 10000);
SharedHandle<Int_t*> tk_quality("tk_quality", &m_entry_number, 10000);
SharedHandle<Float_t> met_pfmet("met_pfmet", &m_entry_number);
SharedHandle<Float_t> met_phi_pfmet("met_phi_pfmet", &m_entry_number);
SharedHandle<Float_t> met_sumet_pfmet("met_sumet_pfmet", &m_entry_number);
SharedHandle<Float_t> met_mEtSig_pfmet("met_mEtSig_pfmet", &m_entry_number);
SharedHandle<Float_t> met_significance_pfmet("met_significance_pfmet", &m_entry_number);
SharedHandle<Float_t> met_pfmetType1("met_pfmetType1", &m_entry_number);
SharedHandle<Float_t> met_phi_pfmetType1("met_phi_pfmetType1", &m_entry_number);
SharedHandle<Float_t> met_sumet_pfmetType1("met_sumet_pfmetType1", &m_entry_number);
SharedHandle<Float_t> met_mEtSig_pfmetType1("met_mEtSig_pfmetType1", &m_entry_number);
SharedHandle<Float_t> met_significance_pfmetType1("met_significance_pfmetType1", &m_entry_number);
SharedHandle<Int_t> el_std_n("el_std_n", &m_entry_number);
SharedHandle<TClonesArray*> el_std_p4("el_std_p4", &m_entry_number);
SharedHandle<TClonesArray*> el_std_sc("el_std_sc", &m_entry_number);
SharedHandle<Int_t*> el_std_scind("el_std_scind", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_sieie("el_std_sieie", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_sieiesc("el_std_sieiesc", &m_entry_number, 100);
SharedHandle<Int_t*> el_std_hp_expin("el_std_hp_expin", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_detain("el_std_detain", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_dphiin("el_std_dphiin", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_eopin("el_std_eopin", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_fbrem("el_std_fbrem", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_ip_gsf("el_std_ip_gsf", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_hoe("el_std_hoe", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_eseedopin("el_std_eseedopin", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_tkiso03("el_std_tkiso03", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_ecaliso03("el_std_ecaliso03", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_ecaliso04("el_std_ecaliso04", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_hcaliso03("el_std_hcaliso03", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_hcaliso04("el_std_hcaliso04", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_dcot("el_std_dcot", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_dist("el_std_dist", &m_entry_number, 100);
SharedHandle<Int_t*> el_std_tkind("el_std_tkind", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_d0("el_std_d0", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_z0("el_std_z0", &m_entry_number, 100);
SharedHandle<TClonesArray*> el_std_posvtx("el_std_posvtx", &m_entry_number);
SharedHandle<Float_t*> el_std_ip_ctf("el_std_ip_ctf", &m_entry_number, 100);
SharedHandle<Bool_t*> el_std_tkdrv("el_std_tkdrv", &m_entry_number, 100);
SharedHandle<Bool_t*> el_std_ecaldrv("el_std_ecaldrv", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_pfiso_charged("el_std_pfiso_charged", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_pfiso_neutral("el_std_pfiso_neutral", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_pfiso_photon("el_std_pfiso_photon", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_conv_vtxProb("el_std_conv_vtxProb", &m_entry_number, 100);
SharedHandle<Int_t*> el_std_conv("el_std_conv", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_pin("el_std_pin", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_mva_nontrig("el_std_mva_nontrig", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_mva_trig("el_std_mva_trig", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_regr_energy("el_std_regr_energy", &m_entry_number, 100);
SharedHandle<Float_t*> el_std_regr_energyerr("el_std_regr_energyerr", &m_entry_number, 100);
SharedHandle<Int_t> mu_glo_n("mu_glo_n", &m_entry_number);
SharedHandle<TClonesArray*> mu_glo_p4("mu_glo_p4", &m_entry_number);
SharedHandle<Float_t*> mu_glo_dof("mu_glo_dof", &m_entry_number, 100);
SharedHandle<Float_t*> mu_glo_chi2("mu_glo_chi2", &m_entry_number, 100);
SharedHandle<Int_t*> mu_glo_type("mu_glo_type", &m_entry_number, 100);
SharedHandle<Int_t*> mu_glo_nmatches("mu_glo_nmatches", &m_entry_number, 100);
SharedHandle<TClonesArray*> mu_glo_posvtx("mu_glo_posvtx", &m_entry_number);
SharedHandle<Int_t*> mu_glo_losthits("mu_glo_losthits", &m_entry_number, 100);
SharedHandle<Int_t*> mu_glo_validhits("mu_glo_validhits", &m_entry_number, 100);
SharedHandle<Int_t*> mu_glo_innerhits("mu_glo_innerhits", &m_entry_number, 100);
SharedHandle<Int_t*> mu_glo_pixelhits("mu_glo_pixelhits", &m_entry_number, 100);
SharedHandle<Int_t*> mu_glo_validChmbhits("mu_glo_validChmbhits", &m_entry_number, 100);
SharedHandle<Float_t*> mu_glo_tkpterr("mu_glo_tkpterr", &m_entry_number, 100);
SharedHandle<Float_t*> mu_glo_ecaliso03("mu_glo_ecaliso03", &m_entry_number, 100);
SharedHandle<Float_t*> mu_glo_hcaliso03("mu_glo_hcaliso03", &m_entry_number, 100);
SharedHandle<Float_t*> mu_glo_tkiso03("mu_glo_tkiso03", &m_entry_number, 100);
SharedHandle<Float_t*> mu_glo_dz("mu_glo_dz", &m_entry_number, 100);
SharedHandle<Int_t*> mu_tkLayers("mu_tkLayers", &m_entry_number, 100);
SharedHandle<Float_t*> mu_glo_chhadiso04("mu_glo_chhadiso04", &m_entry_number, 100);
SharedHandle<Float_t*> mu_glo_nehadiso04("mu_glo_nehadiso04", &m_entry_number, 100);
SharedHandle<Float_t*> mu_glo_photiso04("mu_glo_photiso04", &m_entry_number, 100);
SharedHandle<Float_t*> mu_dbCorr("mu_dbCorr", &m_entry_number, 100);
SharedHandle<Int_t> pho_n("pho_n", &m_entry_number);
SharedHandle<Float_t*> pho_crackcorr("pho_crackcorr", &m_entry_number, 100);
SharedHandle<Float_t*> pho_localcorr("pho_localcorr", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEB("pho_isEB", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEE("pho_isEE", &m_entry_number, 100);
SharedHandle<Float_t*> pho_see("pho_see", &m_entry_number, 100);
SharedHandle<Float_t*> pho_sieie("pho_sieie", &m_entry_number, 100);
SharedHandle<Float_t*> pho_sipip("pho_sipip", &m_entry_number, 100);
SharedHandle<Float_t*> pho_sieip("pho_sieip", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e1x5("pho_e1x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e3x3("pho_e3x3", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e5x5("pho_e5x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_emaxxtal("pho_emaxxtal", &m_entry_number, 100);
SharedHandle<Float_t*> pho_hoe("pho_hoe", &m_entry_number, 100);
SharedHandle<Float_t*> pho_r1x5("pho_r1x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_r2x5("pho_r2x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_r9("pho_r9", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEBGap("pho_isEBGap", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEEGap("pho_isEEGap", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEBEEGap("pho_isEBEEGap", &m_entry_number, 100);
SharedHandle<Float_t*> pho_zernike20("pho_zernike20", &m_entry_number, 100);
SharedHandle<Float_t*> pho_zernike42("pho_zernike42", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2nd("pho_e2nd", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5max("pho_e2x5max", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5right("pho_e2x5right", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5left("pho_e2x5left", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5top("pho_e2x5top", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5bottom("pho_e2x5bottom", &m_entry_number, 100);
SharedHandle<Float_t*> pho_eright("pho_eright", &m_entry_number, 100);
SharedHandle<Float_t*> pho_eleft("pho_eleft", &m_entry_number, 100);
SharedHandle<Float_t*> pho_etop("pho_etop", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ebottom("pho_ebottom", &m_entry_number, 100);
SharedHandle<Float_t*> pho_r19("pho_r19", &m_entry_number, 100);
SharedHandle<Float_t*> pho_maxoraw("pho_maxoraw", &m_entry_number, 100);
SharedHandle<Float_t*> pho_cep("pho_cep", &m_entry_number, 100);
SharedHandle<Float_t*> pho_lambdaratio("pho_lambdaratio", &m_entry_number, 100);
SharedHandle<Float_t*> pho_lambdadivcov("pho_lambdadivcov", &m_entry_number, 100);
SharedHandle<Float_t*> pho_etawidth("pho_etawidth", &m_entry_number, 100);
SharedHandle<Float_t*> pho_brem("pho_brem", &m_entry_number, 100);
SharedHandle<Float_t*> pho_smaj("pho_smaj", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x2("pho_e2x2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_time("pho_seed_time", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_outoftimechi2("pho_seed_outoftimechi2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_chi2("pho_seed_chi2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_recoflag("pho_seed_recoflag", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_severity("pho_seed_severity", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ecalsumetconedr04("pho_ecalsumetconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_hcalsumetconedr04("pho_hcalsumetconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_trksumptsolidconedr04("pho_trksumptsolidconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_trksumpthollowconedr04("pho_trksumpthollowconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ntrksolidconedr04("pho_ntrksolidconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ntrkhollowconedr04("pho_ntrkhollowconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ecalsumetconedr03("pho_ecalsumetconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_hcalsumetconedr03("pho_hcalsumetconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_trksumptsolidconedr03("pho_trksumptsolidconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_trksumpthollowconedr03("pho_trksumpthollowconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ntrksolidconedr03("pho_ntrksolidconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ntrkhollowconedr03("pho_ntrkhollowconedr03", &m_entry_number, 100);
SharedHandle<Int_t*> pho_haspixseed("pho_haspixseed", &m_entry_number, 100);
SharedHandle<Int_t*> pho_hasconvtks("pho_hasconvtks", &m_entry_number, 100);
SharedHandle<Int_t*> pho_nconv("pho_nconv", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_ntracks("pho_conv_ntracks", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_pairinvmass("pho_conv_pairinvmass", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_paircotthetasep("pho_conv_paircotthetasep", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_eoverp("pho_conv_eoverp", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_zofprimvtxfromtrks("pho_conv_zofprimvtxfromtrks", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_distofminapproach("pho_conv_distofminapproach", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_dphitrksatvtx("pho_conv_dphitrksatvtx", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_dphitrksatecal("pho_conv_dphitrksatecal", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_detatrksatecal("pho_conv_detatrksatecal", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_d0("pho_conv_tk1_d0", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_pout("pho_conv_tk1_pout", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_pin("pho_conv_tk1_pin", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_d0("pho_conv_tk2_d0", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_pout("pho_conv_tk2_pout", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_pin("pho_conv_tk2_pin", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_dz("pho_conv_tk1_dz", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_dzerr("pho_conv_tk1_dzerr", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_tk1_nh("pho_conv_tk1_nh", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_dz("pho_conv_tk2_dz", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_dzerr("pho_conv_tk2_dzerr", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_tk2_nh("pho_conv_tk2_nh", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_ch1ch2("pho_conv_ch1ch2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_chi2("pho_conv_chi2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_chi2_probability("pho_conv_chi2_probability", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_validvtx("pho_conv_validvtx", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_MVALikelihood("pho_conv_MVALikelihood", &m_entry_number, 100);
SharedHandle<TClonesArray*> pho_p4("pho_p4", &m_entry_number);
SharedHandle<TClonesArray*> pho_calopos("pho_calopos", &m_entry_number);
SharedHandle<TClonesArray*> pho_conv_vtx("pho_conv_vtx", &m_entry_number);
SharedHandle<TClonesArray*> pho_conv_pair_momentum("pho_conv_pair_momentum", &m_entry_number);
SharedHandle<TClonesArray*> pho_conv_refitted_momentum("pho_conv_refitted_momentum", &m_entry_number);
SharedHandle<TClonesArray*> pho_conv_vertexcorrected_p4("pho_conv_vertexcorrected_p4", &m_entry_number);
SharedHandle<Int_t*> pho_scind("pho_scind", &m_entry_number, 100);
SharedHandle<Float_t*> pho_residCorrEnergy("pho_residCorrEnergy", &m_entry_number, 100);
SharedHandle<Float_t*> pho_residCorrResn("pho_residCorrResn", &m_entry_number, 100);
SharedHandle<Float_t*> pho_regr_energy("pho_regr_energy", &m_entry_number, 100);
SharedHandle<Float_t*> pho_regr_energyerr("pho_regr_energyerr", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isconv("pho_isconv", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myneutral01("pho_pfiso_myneutral01", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myneutral02("pho_pfiso_myneutral02", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myneutral03("pho_pfiso_myneutral03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myneutral04("pho_pfiso_myneutral04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myneutral05("pho_pfiso_myneutral05", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myneutral06("pho_pfiso_myneutral06", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myphoton01("pho_pfiso_myphoton01", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myphoton02("pho_pfiso_myphoton02", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myphoton03("pho_pfiso_myphoton03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myphoton04("pho_pfiso_myphoton04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myphoton05("pho_pfiso_myphoton05", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_myphoton06("pho_pfiso_myphoton06", &m_entry_number, 100);
SharedHandle<vector<vector<float> >*> pho_pfiso_mycharged01("pho_pfiso_mycharged01", &m_entry_number);
SharedHandle<vector<vector<float> >*> pho_pfiso_mycharged02("pho_pfiso_mycharged02", &m_entry_number);
SharedHandle<vector<vector<float> >*> pho_pfiso_mycharged03("pho_pfiso_mycharged03", &m_entry_number);
SharedHandle<vector<vector<float> >*> pho_pfiso_mycharged04("pho_pfiso_mycharged04", &m_entry_number);
SharedHandle<vector<vector<float> >*> pho_pfiso_mycharged05("pho_pfiso_mycharged05", &m_entry_number);
SharedHandle<vector<vector<float> >*> pho_pfiso_mycharged06("pho_pfiso_mycharged06", &m_entry_number);
SharedHandle<Int_t*> pho_isPFPhoton("pho_isPFPhoton", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isPFElectron("pho_isPFElectron", &m_entry_number, 100);
SharedHandle<Float_t*> pho_must("pho_must", &m_entry_number, 100);
SharedHandle<Int_t*> pho_mustnc("pho_mustnc", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfpresh1("pho_pfpresh1", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfpresh2("pho_pfpresh2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_mustenergy("pho_mustenergy", &m_entry_number, 100);
SharedHandle<Float_t*> pho_mustenergyout("pho_mustenergyout", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pflowE("pho_pflowE", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfdeta("pho_pfdeta", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfdphi("pho_pfdphi", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfclusrms("pho_pfclusrms", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfclusrmsmust("pho_pfclusrmsmust", &m_entry_number, 100);
SharedHandle<Float_t*> pho_eseffsixix("pho_eseffsixix", &m_entry_number, 100);
SharedHandle<Float_t*> pho_eseffsiyiy("pho_eseffsiyiy", &m_entry_number, 100);
SharedHandle<Float_t*> pho_hoe_bc("pho_hoe_bc", &m_entry_number, 100);
SharedHandle<Int_t*> pho_biphi("pho_biphi", &m_entry_number, 100);
SharedHandle<Int_t*> pho_bieta("pho_bieta", &m_entry_number, 100);
SharedHandle<Float_t*> pho_betacry("pho_betacry", &m_entry_number, 100);
SharedHandle<Float_t*> pho_phicry("pho_phicry", &m_entry_number, 100);
SharedHandle<Int_t> conv_n("conv_n", &m_entry_number);
SharedHandle<TClonesArray*> conv_p4("conv_p4", &m_entry_number);
SharedHandle<Int_t*> conv_ntracks("conv_ntracks", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_pairinvmass("conv_pairinvmass", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_paircotthetasep("conv_paircotthetasep", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_eoverp("conv_eoverp", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_distofminapproach("conv_distofminapproach", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_dphitrksatvtx("conv_dphitrksatvtx", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_dphitrksatecal("conv_dphitrksatecal", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_detatrksatecal("conv_detatrksatecal", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_dxy("conv_dxy", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_dz("conv_dz", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_lxy("conv_lxy", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_lz("conv_lz", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_zofprimvtxfromtrks("conv_zofprimvtxfromtrks", &m_entry_number, 2000);
SharedHandle<vector<vector<unsigned short> >*> conv_nHitsBeforeVtx("conv_nHitsBeforeVtx", &m_entry_number);
SharedHandle<Int_t*> conv_nSharedHits("conv_nSharedHits", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_validvtx("conv_validvtx", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_MVALikelihood("conv_MVALikelihood", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_chi2("conv_chi2", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_chi2_probability("conv_chi2_probability", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_vtx_xErr("conv_vtx_xErr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_vtx_yErr("conv_vtx_yErr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_vtx_zErr("conv_vtx_zErr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_dz("conv_tk1_dz", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_dz("conv_tk2_dz", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_dzerr("conv_tk1_dzerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_dzerr("conv_tk2_dzerr", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_tk1_nh("conv_tk1_nh", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_tk2_nh("conv_tk2_nh", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_ch1ch2("conv_ch1ch2", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_d0("conv_tk1_d0", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_pout("conv_tk1_pout", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_pin("conv_tk1_pin", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_d0("conv_tk2_d0", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_pout("conv_tk2_pout", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_pin("conv_tk2_pin", &m_entry_number, 2000);
SharedHandle<TClonesArray*> conv_vtx("conv_vtx", &m_entry_number);
SharedHandle<Float_t*> conv_tk1_pterr("conv_tk1_pterr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_pterr("conv_tk2_pterr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_etaerr("conv_tk1_etaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_etaerr("conv_tk2_etaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_thetaerr("conv_tk1_thetaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_thetaerr("conv_tk2_thetaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_phierr("conv_tk1_phierr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_phierr("conv_tk2_phierr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_lambdaerr("conv_tk1_lambdaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_lambdaerr("conv_tk2_lambdaerr", &m_entry_number, 2000);
SharedHandle<TClonesArray*> conv_pair_momentum("conv_pair_momentum", &m_entry_number);
SharedHandle<TClonesArray*> conv_refitted_momentum("conv_refitted_momentum", &m_entry_number);
SharedHandle<TClonesArray*> conv_singleleg_momentum("conv_singleleg_momentum", &m_entry_number);
SharedHandle<Int_t> process_id("process_id", &m_entry_number);
SharedHandle<Float_t> weight("weight", &m_entry_number);
SharedHandle<Float_t> pthat("pthat", &m_entry_number);
SharedHandle<Int_t> gp_n("gp_n", &m_entry_number);
SharedHandle<TClonesArray*> gp_p4("gp_p4", &m_entry_number);
SharedHandle<TClonesArray*> gp_vtx("gp_vtx", &m_entry_number);
SharedHandle<Short_t*> gp_status("gp_status", &m_entry_number, 10000);
SharedHandle<Short_t*> gp_pdgid("gp_pdgid", &m_entry_number, 10000);
SharedHandle<Short_t*> gp_mother("gp_mother", &m_entry_number, 10000);
SharedHandle<Int_t> gv_n("gv_n", &m_entry_number);
SharedHandle<TClonesArray*> gv_pos("gv_pos", &m_entry_number);
SharedHandle<Int_t> pu_n("pu_n", &m_entry_number);
SharedHandle<vector<float>*> pu_zpos("pu_zpos", &m_entry_number);
SharedHandle<vector<float>*> pu_sumpt_lowpt("pu_sumpt_lowpt", &m_entry_number);
SharedHandle<vector<float>*> pu_sumpt_highpt("pu_sumpt_highpt", &m_entry_number);
SharedHandle<vector<int>*> pu_ntrks_lowpt("pu_ntrks_lowpt", &m_entry_number);
SharedHandle<vector<int>*> pu_ntrks_highpt("pu_ntrks_highpt", &m_entry_number);
SharedHandle<Int_t> vtx_std_n("vtx_std_n", &m_entry_number);
SharedHandle<Int_t*> vtx_std_ntks("vtx_std_ntks", &m_entry_number, 100);
SharedHandle<Float_t*> vtx_std_x2dof("vtx_std_x2dof", &m_entry_number, 100);
SharedHandle<TClonesArray*> vtx_std_xyz("vtx_std_xyz", &m_entry_number);
SharedHandle<TClonesArray*> vtx_std_dxdydz("vtx_std_dxdydz", &m_entry_number);
SharedHandle<Float_t*> vtx_std_ndof("vtx_std_ndof", &m_entry_number, 100);
SharedHandle<vector<vector<unsigned short> >*> vtx_std_tkind("vtx_std_tkind", &m_entry_number);
SharedHandle<Float_t> rho_algo1("rho_algo1", &m_entry_number);
SharedHandle<Float_t> rho_algo2("rho_algo2", &m_entry_number);
SharedHandle<Float_t> rho_algo3("rho_algo3", &m_entry_number);
SharedHandle<TClonesArray*> bs_xyz("bs_xyz", &m_entry_number);
SharedHandle<Float_t> bs_sigmaZ("bs_sigmaZ", &m_entry_number);
SharedHandle<Float_t> bs_x0Error("bs_x0Error", &m_entry_number);
SharedHandle<Float_t> bs_y0Error("bs_y0Error", &m_entry_number);
SharedHandle<Float_t> bs_z0Error("bs_z0Error", &m_entry_number);
SharedHandle<Float_t> bs_sigmaZ0Error("bs_sigmaZ0Error", &m_entry_number);
SharedHandle<Float_t> met_tcmet("met_tcmet", &m_entry_number);
SharedHandle<Float_t> met_phi_tcmet("met_phi_tcmet", &m_entry_number);
SharedHandle<vector<unsigned short>*> hlt_bit("hlt_bit", &m_entry_number);
SharedHandle<Int_t> hlt_n("hlt_n", &m_entry_number);
SharedHandle<vector<vector<unsigned short> >*> hlt_candpath("hlt_candpath", &m_entry_number);
SharedHandle<vector<string>*> hlt_path_names_HLT("hlt_path_names_HLT", &m_entry_number);
SharedHandle<TClonesArray*> hlt_p4("hlt_p4", &m_entry_number);
SharedHandle<Int_t> jet_algoPF1_n("jet_algoPF1_n", &m_entry_number);
SharedHandle<Float_t*> jet_algoPF1_erescale("jet_algoPF1_erescale", &m_entry_number, 200);
SharedHandle<TClonesArray*> jet_algoPF1_p4("jet_algoPF1_p4", &m_entry_number);
SharedHandle<Float_t*> jet_algoPF1_beta("jet_algoPF1_beta", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_betaStar("jet_algoPF1_betaStar", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_betaStarClassic("jet_algoPF1_betaStarClassic", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_dR2Mean("jet_algoPF1_dR2Mean", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_dRMean("jet_algoPF1_dRMean", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_dZ("jet_algoPF1_dZ", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_frac01("jet_algoPF1_frac01", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_frac02("jet_algoPF1_frac02", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_frac03("jet_algoPF1_frac03", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_frac04("jet_algoPF1_frac04", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_frac05("jet_algoPF1_frac05", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_full_mva("jet_algoPF1_full_mva", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_simple_mva("jet_algoPF1_simple_mva", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_nCharged("jet_algoPF1_nCharged", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_nNeutrals("jet_algoPF1_nNeutrals", &m_entry_number, 200);
SharedHandle<Int_t*> jet_algoPF1_full_wp_level("jet_algoPF1_full_wp_level", &m_entry_number, 200);
SharedHandle<Int_t*> jet_algoPF1_simple_wp_level("jet_algoPF1_simple_wp_level", &m_entry_number, 200);
SharedHandle<Int_t*> jet_algoPF1_cutbased_wp_level("jet_algoPF1_cutbased_wp_level", &m_entry_number, 200);
SharedHandle<Bool_t*> jet_algoPF1_pfloose("jet_algoPF1_pfloose", &m_entry_number, 200);
SharedHandle<Int_t*> jet_algoPF1_ntk("jet_algoPF1_ntk", &m_entry_number, 200);
SharedHandle<vector<vector<unsigned short> >*> jet_algoPF1_tkind("jet_algoPF1_tkind", &m_entry_number);
SharedHandle<Float_t*> jet_algoPF1_area("jet_algoPF1_area", &m_entry_number, 200);
SharedHandle<vector<vector<float> >*> jet_algoPF1_beta_ext("jet_algoPF1_beta_ext", &m_entry_number);
SharedHandle<vector<vector<float> >*> jet_algoPF1_betaStar_ext("jet_algoPF1_betaStar_ext", &m_entry_number);
SharedHandle<vector<vector<float> >*> jet_algoPF1_betaStarClassic_ext("jet_algoPF1_betaStarClassic_ext", &m_entry_number);
SharedHandle<vector<vector<int> >*> jet_algoPF1_full_wp_level_ext("jet_algoPF1_full_wp_level_ext", &m_entry_number);
SharedHandle<vector<vector<int> >*> jet_algoPF1_simple_wp_level_ext("jet_algoPF1_simple_wp_level_ext", &m_entry_number);
SharedHandle<vector<vector<int> >*> jet_algoPF1_cutbased_wp_level_ext("jet_algoPF1_cutbased_wp_level_ext", &m_entry_number);
SharedHandle<vector<vector<float> >*> jet_algoPF1_full_mva_ext("jet_algoPF1_full_mva_ext", &m_entry_number);
SharedHandle<vector<vector<float> >*> jet_algoPF1_simple_mva_ext("jet_algoPF1_simple_mva_ext", &m_entry_number);
SharedHandle<Int_t> jet_algoPF3_n("jet_algoPF3_n", &m_entry_number);
SharedHandle<Float_t*> jet_algoPF3_erescale("jet_algoPF3_erescale", &m_entry_number, 200);
SharedHandle<TClonesArray*> jet_algoPF3_p4("jet_algoPF3_p4", &m_entry_number);
SharedHandle<Float_t*> jet_algoPF3_beta("jet_algoPF3_beta", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_betaStar("jet_algoPF3_betaStar", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_betaStarClassic("jet_algoPF3_betaStarClassic", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_dR2Mean("jet_algoPF3_dR2Mean", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_dRMean("jet_algoPF3_dRMean", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_dZ("jet_algoPF3_dZ", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_frac01("jet_algoPF3_frac01", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_frac02("jet_algoPF3_frac02", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_frac03("jet_algoPF3_frac03", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_frac04("jet_algoPF3_frac04", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_frac05("jet_algoPF3_frac05", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_full_mva("jet_algoPF3_full_mva", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_simple_mva("jet_algoPF3_simple_mva", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_nCharged("jet_algoPF3_nCharged", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_nNeutrals("jet_algoPF3_nNeutrals", &m_entry_number, 200);
SharedHandle<Int_t*> jet_algoPF3_full_wp_level("jet_algoPF3_full_wp_level", &m_entry_number, 200);
SharedHandle<Int_t*> jet_algoPF3_simple_wp_level("jet_algoPF3_simple_wp_level", &m_entry_number, 200);
SharedHandle<Int_t*> jet_algoPF3_cutbased_wp_level("jet_algoPF3_cutbased_wp_level", &m_entry_number, 200);
SharedHandle<Bool_t*> jet_algoPF3_pfloose("jet_algoPF3_pfloose", &m_entry_number, 200);
SharedHandle<Int_t*> jet_algoPF3_ntk("jet_algoPF3_ntk", &m_entry_number, 200);
SharedHandle<vector<vector<unsigned short> >*> jet_algoPF3_tkind("jet_algoPF3_tkind", &m_entry_number);
SharedHandle<Float_t*> jet_algoPF3_area("jet_algoPF3_area", &m_entry_number, 200);
SharedHandle<vector<vector<float> >*> jet_algoPF3_beta_ext("jet_algoPF3_beta_ext", &m_entry_number);
SharedHandle<vector<vector<float> >*> jet_algoPF3_betaStar_ext("jet_algoPF3_betaStar_ext", &m_entry_number);
SharedHandle<vector<vector<float> >*> jet_algoPF3_betaStarClassic_ext("jet_algoPF3_betaStarClassic_ext", &m_entry_number);
SharedHandle<vector<vector<int> >*> jet_algoPF3_full_wp_level_ext("jet_algoPF3_full_wp_level_ext", &m_entry_number);
SharedHandle<vector<vector<int> >*> jet_algoPF3_simple_wp_level_ext("jet_algoPF3_simple_wp_level_ext", &m_entry_number);
SharedHandle<vector<vector<int> >*> jet_algoPF3_cutbased_wp_level_ext("jet_algoPF3_cutbased_wp_level_ext", &m_entry_number);
SharedHandle<vector<vector<float> >*> jet_algoPF3_full_mva_ext("jet_algoPF3_full_mva_ext", &m_entry_number);
SharedHandle<vector<vector<float> >*> jet_algoPF3_simple_mva_ext("jet_algoPF3_simple_mva_ext", &m_entry_number);
SharedHandle<Float_t*> pho_pfRawEnergy("pho_pfRawEnergy", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfe2x2("pho_pfe2x2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfe3x3("pho_pfe3x3", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfe5x5("pho_pfe5x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfsieie("pho_pfsieie", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfsieip("pho_pfsieip", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfsipip("pho_pfsipip", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfemaxxtal("pho_pfemaxxtal", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfe2nd("pho_pfe2nd", &m_entry_number, 100);
SharedHandle<vector<vector<float> >*> vtx_std_mva("vtx_std_mva", &m_entry_number);
SharedHandle<vector<float>*> vtx_std_vertexz("vtx_std_vertexz", &m_entry_number);
SharedHandle<vector<float>*> vtx_std_nconv("vtx_std_nconv", &m_entry_number);
SharedHandle<vector<float>*> vtx_std_nlegs("vtx_std_nlegs", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_pulltoconv("vtx_std_pulltoconv", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_limpulltoconv("vtx_std_limpulltoconv", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_diphopt("vtx_std_diphopt", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_diphopx("vtx_std_diphopx", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_diphopy("vtx_std_diphopy", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_nch("vtx_std_nch", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptmax("vtx_std_ptmax", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumpt("vtx_std_sumpt", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptvtx("vtx_std_ptvtx", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_pxvtx("vtx_std_pxvtx", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_pyvtx("vtx_std_pyvtx", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_acosA("vtx_std_acosA", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptasym("vtx_std_ptasym", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptbal("vtx_std_ptbal", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_nchthr("vtx_std_nchthr", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptmax3("vtx_std_ptmax3", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_thrust("vtx_std_thrust", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumweight("vtx_std_sumweight", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumpt2("vtx_std_sumpt2", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptratio("vtx_std_ptratio", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_pzasym("vtx_std_pzasym", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_spher("vtx_std_spher", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_aplan("vtx_std_aplan", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumpr("vtx_std_sumpr", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumawy("vtx_std_sumawy", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumtrv("vtx_std_sumtrv", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumtwd("vtx_std_sumtwd", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_awytwdasym("vtx_std_awytwdasym", &m_entry_number);
SharedHandle<Int_t> vtx_std_pho1("vtx_std_pho1", &m_entry_number);
SharedHandle<Int_t> vtx_std_pho2("vtx_std_pho2", &m_entry_number);
SharedHandle<vector<int>*> pho_matchingConv("pho_matchingConv", &m_entry_number);
SharedHandle<vector<float>*> vtx_std_evt_mva("vtx_std_evt_mva", &m_entry_number);
SharedHandle<vector<vector<int> >*> vtx_std_ranked_list("vtx_std_ranked_list", &m_entry_number);
SharedHandle<Int_t> vtx_std_sel("vtx_std_sel", &m_entry_number);
SharedHandle<vector<vector<float> >*> pho_tkiso_recvtx_030_002_0000_10_01("pho_tkiso_recvtx_030_002_0000_10_01", &m_entry_number);
SharedHandle<Float_t*> pho_tkiso_badvtx_040_002_0000_10_01("pho_tkiso_badvtx_040_002_0000_10_01", &m_entry_number, 100);
SharedHandle<Int_t*> pho_tkiso_badvtx_id("pho_tkiso_badvtx_id", &m_entry_number, 100);
SharedHandle<Float_t*> pho_pfiso_charged_badvtx_04("pho_pfiso_charged_badvtx_04", &m_entry_number, 100);
SharedHandle<Int_t*> pho_pfiso_charged_badvtx_id("pho_pfiso_charged_badvtx_id", &m_entry_number, 100);
SharedHandle<vector<vector<float> >*> pho_ZeeVal_tkiso_recvtx_030_002_0000_10_01("pho_ZeeVal_tkiso_recvtx_030_002_0000_10_01", &m_entry_number);
SharedHandle<Float_t*> pho_ZeeVal_tkiso_badvtx_040_002_0000_10_01("pho_ZeeVal_tkiso_badvtx_040_002_0000_10_01", &m_entry_number, 100);
SharedHandle<Int_t*> pho_ZeeVal_tkiso_badvtx_id("pho_ZeeVal_tkiso_badvtx_id", &m_entry_number, 100);
SharedHandle<vector<vector<float> >*> pho_mitmva("pho_mitmva", &m_entry_number);
SharedHandle<Float_t*> pho_drtotk_25_99("pho_drtotk_25_99", &m_entry_number, 100);
SharedHandle<Int_t> dipho_n("dipho_n", &m_entry_number);
SharedHandle<Int_t*> dipho_leadind("dipho_leadind", &m_entry_number, 100);
SharedHandle<Int_t*> dipho_subleadind("dipho_subleadind", &m_entry_number, 100);
SharedHandle<Int_t*> dipho_vtxind("dipho_vtxind", &m_entry_number, 100);
SharedHandle<Float_t*> dipho_sumpt("dipho_sumpt", &m_entry_number, 100);
SharedHandle<vector<vector<short> >*> pho_cic6cutlevel_lead("pho_cic6cutlevel_lead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic6passcuts_lead("pho_cic6passcuts_lead", &m_entry_number);
SharedHandle<vector<vector<short> >*> pho_cic6cutlevel_sublead("pho_cic6cutlevel_sublead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic6passcuts_sublead("pho_cic6passcuts_sublead", &m_entry_number);
SharedHandle<vector<vector<short> >*> pho_cic4cutlevel_lead("pho_cic4cutlevel_lead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic4passcuts_lead("pho_cic4passcuts_lead", &m_entry_number);
SharedHandle<vector<vector<short> >*> pho_cic4cutlevel_sublead("pho_cic4cutlevel_sublead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic4passcuts_sublead("pho_cic4passcuts_sublead", &m_entry_number);
SharedHandle<vector<vector<short> >*> pho_cic4pfcutlevel_lead("pho_cic4pfcutlevel_lead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic4pfpasscuts_lead("pho_cic4pfpasscuts_lead", &m_entry_number);
SharedHandle<vector<vector<short> >*> pho_cic4pfcutlevel_sublead("pho_cic4pfcutlevel_sublead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic4pfpasscuts_sublead("pho_cic4pfpasscuts_sublead", &m_entry_number);
SharedHandle<Bool_t*> pho_genmatched("pho_genmatched", &m_entry_number, 100);
SharedHandle<Float_t*> pho_regr_energy_otf("pho_regr_energy_otf", &m_entry_number, 100);
SharedHandle<Float_t*> pho_regr_energyerr_otf("pho_regr_energyerr_otf", &m_entry_number, 100);
SharedHandle<Bool_t*> jet_algoPF1_genMatched("jet_algoPF1_genMatched", &m_entry_number, 200);
SharedHandle<Bool_t*> jet_algoPF1_vbfMatched("jet_algoPF1_vbfMatched", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_genPt("jet_algoPF1_genPt", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF1_genDr("jet_algoPF1_genDr", &m_entry_number, 200);
SharedHandle<Bool_t*> jet_algoPF3_genMatched("jet_algoPF3_genMatched", &m_entry_number, 200);
SharedHandle<Bool_t*> jet_algoPF3_vbfMatched("jet_algoPF3_vbfMatched", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_genPt("jet_algoPF3_genPt", &m_entry_number, 200);
SharedHandle<Float_t*> jet_algoPF3_genDr("jet_algoPF3_genDr", &m_entry_number, 200);
SharedHandle<Float_t*> shiftMET_pt("shiftMET_pt", &m_entry_number, 100);
SharedHandle<Float_t*> shiftMET_phi("shiftMET_phi", &m_entry_number, 100);
SharedHandle<Float_t*> smearMET_pt("smearMET_pt", &m_entry_number, 100);
SharedHandle<Float_t*> smearMET_phi("smearMET_phi", &m_entry_number, 100);
SharedHandle<Float_t*> shiftsmearMET_pt("shiftsmearMET_pt", &m_entry_number, 100);
SharedHandle<Float_t*> shiftsmearMET_phi("shiftsmearMET_phi", &m_entry_number, 100);
SharedHandle<Float_t*> shiftscaleMET_pt("shiftscaleMET_pt", &m_entry_number, 100);
SharedHandle<Float_t*> shiftscaleMET_phi("shiftscaleMET_phi", &m_entry_number, 100);
SharedHandle<Float_t*> shiftMET_eta("shiftMET_eta", &m_entry_number, 100);
SharedHandle<Float_t*> shiftMET_e("shiftMET_e", &m_entry_number, 100);
SharedHandle<Float_t*> shiftscaleMET_eta("shiftscaleMET_eta", &m_entry_number, 100);
SharedHandle<Float_t*> shiftscaleMET_e("shiftscaleMET_e", &m_entry_number, 100);
SharedHandle<Int_t> gh_gen2reco1("gh_gen2reco1", &m_entry_number);
SharedHandle<Int_t> gh_gen2reco2("gh_gen2reco2", &m_entry_number);
SharedHandle<Int_t> gh_vbfq1_pdgid("gh_vbfq1_pdgid", &m_entry_number);
SharedHandle<Int_t> gh_vbfq2_pdgid("gh_vbfq2_pdgid", &m_entry_number);
SharedHandle<Int_t> gh_vh_pdgid("gh_vh_pdgid", &m_entry_number);
SharedHandle<Int_t> gh_vh1_pdgid("gh_vh1_pdgid", &m_entry_number);
SharedHandle<Int_t> gh_vh2_pdgid("gh_vh2_pdgid", &m_entry_number);
SharedHandle<TClonesArray*> gh_higgs_p4("gh_higgs_p4", &m_entry_number);
SharedHandle<TClonesArray*> gh_pho1_p4("gh_pho1_p4", &m_entry_number);
SharedHandle<TClonesArray*> gh_pho2_p4("gh_pho2_p4", &m_entry_number);
SharedHandle<TClonesArray*> gh_vbfq1_p4("gh_vbfq1_p4", &m_entry_number);
SharedHandle<TClonesArray*> gh_vbfq2_p4("gh_vbfq2_p4", &m_entry_number);
SharedHandle<TClonesArray*> gh_vh1_p4("gh_vh1_p4", &m_entry_number);
SharedHandle<TClonesArray*> gh_vh2_p4("gh_vh2_p4", &m_entry_number);

void connect_variables(TTree* t){

  event.ReadFrom(t);
  lumis.ReadFrom(t);
  run.ReadFrom(t);
  bx.ReadFrom(t);
  sc_p4.ReadFrom(t);
  sc_xyz.ReadFrom(t);
  sc_n.ReadFrom(t);
  sc_sphi.ReadFrom(t);
  sc_seta.ReadFrom(t);
  sc_raw.ReadFrom(t);
  sc_pre.ReadFrom(t);
  sc_bcseedind.ReadFrom(t);
  sc_nbc.ReadFrom(t);
  ecalhit_n.ReadFrom(t);
  ecalhit_detid.ReadFrom(t);
  ecalhit_p4.ReadFrom(t);
  bc_n.ReadFrom(t);
  bc_p4.ReadFrom(t);
  tk_n.ReadFrom(t);
  tk_p4.ReadFrom(t);
  tk_vtx_pos.ReadFrom(t);
  tk_nhits.ReadFrom(t);
  tk_nlosthit.ReadFrom(t);
  tk_quality.ReadFrom(t);
  met_pfmet.ReadFrom(t);
  met_phi_pfmet.ReadFrom(t);
  met_sumet_pfmet.ReadFrom(t);
  met_mEtSig_pfmet.ReadFrom(t);
  met_significance_pfmet.ReadFrom(t);
  met_pfmetType1.ReadFrom(t);
  met_phi_pfmetType1.ReadFrom(t);
  met_sumet_pfmetType1.ReadFrom(t);
  met_mEtSig_pfmetType1.ReadFrom(t);
  met_significance_pfmetType1.ReadFrom(t);
  el_std_n.ReadFrom(t);
  el_std_p4.ReadFrom(t);
  el_std_sc.ReadFrom(t);
  el_std_scind.ReadFrom(t);
  el_std_sieie.ReadFrom(t);
  el_std_sieiesc.ReadFrom(t);
  el_std_hp_expin.ReadFrom(t);
  el_std_detain.ReadFrom(t);
  el_std_dphiin.ReadFrom(t);
  el_std_eopin.ReadFrom(t);
  el_std_fbrem.ReadFrom(t);
  el_std_ip_gsf.ReadFrom(t);
  el_std_hoe.ReadFrom(t);
  el_std_eseedopin.ReadFrom(t);
  el_std_tkiso03.ReadFrom(t);
  el_std_ecaliso03.ReadFrom(t);
  el_std_ecaliso04.ReadFrom(t);
  el_std_hcaliso03.ReadFrom(t);
  el_std_hcaliso04.ReadFrom(t);
  el_std_dcot.ReadFrom(t);
  el_std_dist.ReadFrom(t);
  el_std_tkind.ReadFrom(t);
  el_std_d0.ReadFrom(t);
  el_std_z0.ReadFrom(t);
  el_std_posvtx.ReadFrom(t);
  el_std_ip_ctf.ReadFrom(t);
  el_std_tkdrv.ReadFrom(t);
  el_std_ecaldrv.ReadFrom(t);
  el_std_pfiso_charged.ReadFrom(t);
  el_std_pfiso_neutral.ReadFrom(t);
  el_std_pfiso_photon.ReadFrom(t);
  el_std_conv_vtxProb.ReadFrom(t);
  el_std_conv.ReadFrom(t);
  el_std_pin.ReadFrom(t);
  el_std_mva_nontrig.ReadFrom(t);
  el_std_mva_trig.ReadFrom(t);
  el_std_regr_energy.ReadFrom(t);
  el_std_regr_energyerr.ReadFrom(t);
  mu_glo_n.ReadFrom(t);
  mu_glo_p4.ReadFrom(t);
  mu_glo_dof.ReadFrom(t);
  mu_glo_chi2.ReadFrom(t);
  mu_glo_type.ReadFrom(t);
  mu_glo_nmatches.ReadFrom(t);
  mu_glo_posvtx.ReadFrom(t);
  mu_glo_losthits.ReadFrom(t);
  mu_glo_validhits.ReadFrom(t);
  mu_glo_innerhits.ReadFrom(t);
  mu_glo_pixelhits.ReadFrom(t);
  mu_glo_validChmbhits.ReadFrom(t);
  mu_glo_tkpterr.ReadFrom(t);
  mu_glo_ecaliso03.ReadFrom(t);
  mu_glo_hcaliso03.ReadFrom(t);
  mu_glo_tkiso03.ReadFrom(t);
  mu_glo_dz.ReadFrom(t);
  mu_tkLayers.ReadFrom(t);
  mu_glo_chhadiso04.ReadFrom(t);
  mu_glo_nehadiso04.ReadFrom(t);
  mu_glo_photiso04.ReadFrom(t);
  mu_dbCorr.ReadFrom(t);
  pho_n.ReadFrom(t);
  pho_crackcorr.ReadFrom(t);
  pho_localcorr.ReadFrom(t);
  pho_isEB.ReadFrom(t);
  pho_isEE.ReadFrom(t);
  pho_see.ReadFrom(t);
  pho_sieie.ReadFrom(t);
  pho_sipip.ReadFrom(t);
  pho_sieip.ReadFrom(t);
  pho_e1x5.ReadFrom(t);
  pho_e3x3.ReadFrom(t);
  pho_e5x5.ReadFrom(t);
  pho_emaxxtal.ReadFrom(t);
  pho_hoe.ReadFrom(t);
  pho_r1x5.ReadFrom(t);
  pho_r2x5.ReadFrom(t);
  pho_r9.ReadFrom(t);
  pho_isEBGap.ReadFrom(t);
  pho_isEEGap.ReadFrom(t);
  pho_isEBEEGap.ReadFrom(t);
  pho_zernike20.ReadFrom(t);
  pho_zernike42.ReadFrom(t);
  pho_e2nd.ReadFrom(t);
  pho_e2x5max.ReadFrom(t);
  pho_e2x5right.ReadFrom(t);
  pho_e2x5left.ReadFrom(t);
  pho_e2x5top.ReadFrom(t);
  pho_e2x5bottom.ReadFrom(t);
  pho_eright.ReadFrom(t);
  pho_eleft.ReadFrom(t);
  pho_etop.ReadFrom(t);
  pho_ebottom.ReadFrom(t);
  pho_r19.ReadFrom(t);
  pho_maxoraw.ReadFrom(t);
  pho_cep.ReadFrom(t);
  pho_lambdaratio.ReadFrom(t);
  pho_lambdadivcov.ReadFrom(t);
  pho_etawidth.ReadFrom(t);
  pho_brem.ReadFrom(t);
  pho_smaj.ReadFrom(t);
  pho_e2x2.ReadFrom(t);
  pho_seed_time.ReadFrom(t);
  pho_seed_outoftimechi2.ReadFrom(t);
  pho_seed_chi2.ReadFrom(t);
  pho_seed_recoflag.ReadFrom(t);
  pho_seed_severity.ReadFrom(t);
  pho_ecalsumetconedr04.ReadFrom(t);
  pho_hcalsumetconedr04.ReadFrom(t);
  pho_trksumptsolidconedr04.ReadFrom(t);
  pho_trksumpthollowconedr04.ReadFrom(t);
  pho_ntrksolidconedr04.ReadFrom(t);
  pho_ntrkhollowconedr04.ReadFrom(t);
  pho_ecalsumetconedr03.ReadFrom(t);
  pho_hcalsumetconedr03.ReadFrom(t);
  pho_trksumptsolidconedr03.ReadFrom(t);
  pho_trksumpthollowconedr03.ReadFrom(t);
  pho_ntrksolidconedr03.ReadFrom(t);
  pho_ntrkhollowconedr03.ReadFrom(t);
  pho_haspixseed.ReadFrom(t);
  pho_hasconvtks.ReadFrom(t);
  pho_nconv.ReadFrom(t);
  pho_conv_ntracks.ReadFrom(t);
  pho_conv_pairinvmass.ReadFrom(t);
  pho_conv_paircotthetasep.ReadFrom(t);
  pho_conv_eoverp.ReadFrom(t);
  pho_conv_zofprimvtxfromtrks.ReadFrom(t);
  pho_conv_distofminapproach.ReadFrom(t);
  pho_conv_dphitrksatvtx.ReadFrom(t);
  pho_conv_dphitrksatecal.ReadFrom(t);
  pho_conv_detatrksatecal.ReadFrom(t);
  pho_conv_tk1_d0.ReadFrom(t);
  pho_conv_tk1_pout.ReadFrom(t);
  pho_conv_tk1_pin.ReadFrom(t);
  pho_conv_tk2_d0.ReadFrom(t);
  pho_conv_tk2_pout.ReadFrom(t);
  pho_conv_tk2_pin.ReadFrom(t);
  pho_conv_tk1_dz.ReadFrom(t);
  pho_conv_tk1_dzerr.ReadFrom(t);
  pho_conv_tk1_nh.ReadFrom(t);
  pho_conv_tk2_dz.ReadFrom(t);
  pho_conv_tk2_dzerr.ReadFrom(t);
  pho_conv_tk2_nh.ReadFrom(t);
  pho_conv_ch1ch2.ReadFrom(t);
  pho_conv_chi2.ReadFrom(t);
  pho_conv_chi2_probability.ReadFrom(t);
  pho_conv_validvtx.ReadFrom(t);
  pho_conv_MVALikelihood.ReadFrom(t);
  pho_p4.ReadFrom(t);
  pho_calopos.ReadFrom(t);
  pho_conv_vtx.ReadFrom(t);
  pho_conv_pair_momentum.ReadFrom(t);
  pho_conv_refitted_momentum.ReadFrom(t);
  pho_conv_vertexcorrected_p4.ReadFrom(t);
  pho_scind.ReadFrom(t);
  pho_residCorrEnergy.ReadFrom(t);
  pho_residCorrResn.ReadFrom(t);
  pho_regr_energy.ReadFrom(t);
  pho_regr_energyerr.ReadFrom(t);
  pho_isconv.ReadFrom(t);
  pho_pfiso_myneutral01.ReadFrom(t);
  pho_pfiso_myneutral02.ReadFrom(t);
  pho_pfiso_myneutral03.ReadFrom(t);
  pho_pfiso_myneutral04.ReadFrom(t);
  pho_pfiso_myneutral05.ReadFrom(t);
  pho_pfiso_myneutral06.ReadFrom(t);
  pho_pfiso_myphoton01.ReadFrom(t);
  pho_pfiso_myphoton02.ReadFrom(t);
  pho_pfiso_myphoton03.ReadFrom(t);
  pho_pfiso_myphoton04.ReadFrom(t);
  pho_pfiso_myphoton05.ReadFrom(t);
  pho_pfiso_myphoton06.ReadFrom(t);
  pho_pfiso_mycharged01.ReadFrom(t);
  pho_pfiso_mycharged02.ReadFrom(t);
  pho_pfiso_mycharged03.ReadFrom(t);
  pho_pfiso_mycharged04.ReadFrom(t);
  pho_pfiso_mycharged05.ReadFrom(t);
  pho_pfiso_mycharged06.ReadFrom(t);
  pho_isPFPhoton.ReadFrom(t);
  pho_isPFElectron.ReadFrom(t);
  pho_must.ReadFrom(t);
  pho_mustnc.ReadFrom(t);
  pho_pfpresh1.ReadFrom(t);
  pho_pfpresh2.ReadFrom(t);
  pho_mustenergy.ReadFrom(t);
  pho_mustenergyout.ReadFrom(t);
  pho_pflowE.ReadFrom(t);
  pho_pfdeta.ReadFrom(t);
  pho_pfdphi.ReadFrom(t);
  pho_pfclusrms.ReadFrom(t);
  pho_pfclusrmsmust.ReadFrom(t);
  pho_eseffsixix.ReadFrom(t);
  pho_eseffsiyiy.ReadFrom(t);
  pho_hoe_bc.ReadFrom(t);
  pho_biphi.ReadFrom(t);
  pho_bieta.ReadFrom(t);
  pho_betacry.ReadFrom(t);
  pho_phicry.ReadFrom(t);
  conv_n.ReadFrom(t);
  conv_p4.ReadFrom(t);
  conv_ntracks.ReadFrom(t);
  conv_pairinvmass.ReadFrom(t);
  conv_paircotthetasep.ReadFrom(t);
  conv_eoverp.ReadFrom(t);
  conv_distofminapproach.ReadFrom(t);
  conv_dphitrksatvtx.ReadFrom(t);
  conv_dphitrksatecal.ReadFrom(t);
  conv_detatrksatecal.ReadFrom(t);
  conv_dxy.ReadFrom(t);
  conv_dz.ReadFrom(t);
  conv_lxy.ReadFrom(t);
  conv_lz.ReadFrom(t);
  conv_zofprimvtxfromtrks.ReadFrom(t);
  conv_nHitsBeforeVtx.ReadFrom(t);
  conv_nSharedHits.ReadFrom(t);
  conv_validvtx.ReadFrom(t);
  conv_MVALikelihood.ReadFrom(t);
  conv_chi2.ReadFrom(t);
  conv_chi2_probability.ReadFrom(t);
  conv_vtx_xErr.ReadFrom(t);
  conv_vtx_yErr.ReadFrom(t);
  conv_vtx_zErr.ReadFrom(t);
  conv_tk1_dz.ReadFrom(t);
  conv_tk2_dz.ReadFrom(t);
  conv_tk1_dzerr.ReadFrom(t);
  conv_tk2_dzerr.ReadFrom(t);
  conv_tk1_nh.ReadFrom(t);
  conv_tk2_nh.ReadFrom(t);
  conv_ch1ch2.ReadFrom(t);
  conv_tk1_d0.ReadFrom(t);
  conv_tk1_pout.ReadFrom(t);
  conv_tk1_pin.ReadFrom(t);
  conv_tk2_d0.ReadFrom(t);
  conv_tk2_pout.ReadFrom(t);
  conv_tk2_pin.ReadFrom(t);
  conv_vtx.ReadFrom(t);
  conv_tk1_pterr.ReadFrom(t);
  conv_tk2_pterr.ReadFrom(t);
  conv_tk1_etaerr.ReadFrom(t);
  conv_tk2_etaerr.ReadFrom(t);
  conv_tk1_thetaerr.ReadFrom(t);
  conv_tk2_thetaerr.ReadFrom(t);
  conv_tk1_phierr.ReadFrom(t);
  conv_tk2_phierr.ReadFrom(t);
  conv_tk1_lambdaerr.ReadFrom(t);
  conv_tk2_lambdaerr.ReadFrom(t);
  conv_pair_momentum.ReadFrom(t);
  conv_refitted_momentum.ReadFrom(t);
  conv_singleleg_momentum.ReadFrom(t);
  process_id.ReadFrom(t);
  weight.ReadFrom(t);
  pthat.ReadFrom(t);
  gp_n.ReadFrom(t);
  gp_p4.ReadFrom(t);
  gp_vtx.ReadFrom(t);
  gp_status.ReadFrom(t);
  gp_pdgid.ReadFrom(t);
  gp_mother.ReadFrom(t);
  gv_n.ReadFrom(t);
  gv_pos.ReadFrom(t);
  pu_n.ReadFrom(t);
  pu_zpos.ReadFrom(t);
  pu_sumpt_lowpt.ReadFrom(t);
  pu_sumpt_highpt.ReadFrom(t);
  pu_ntrks_lowpt.ReadFrom(t);
  pu_ntrks_highpt.ReadFrom(t);
  vtx_std_n.ReadFrom(t);
  vtx_std_ntks.ReadFrom(t);
  vtx_std_x2dof.ReadFrom(t);
  vtx_std_xyz.ReadFrom(t);
  vtx_std_dxdydz.ReadFrom(t);
  vtx_std_ndof.ReadFrom(t);
  vtx_std_tkind.ReadFrom(t);
  rho_algo1.ReadFrom(t);
  rho_algo2.ReadFrom(t);
  rho_algo3.ReadFrom(t);
  bs_xyz.ReadFrom(t);
  bs_sigmaZ.ReadFrom(t);
  bs_x0Error.ReadFrom(t);
  bs_y0Error.ReadFrom(t);
  bs_z0Error.ReadFrom(t);
  bs_sigmaZ0Error.ReadFrom(t);
  met_tcmet.ReadFrom(t);
  met_phi_tcmet.ReadFrom(t);
  hlt_bit.ReadFrom(t);
  hlt_n.ReadFrom(t);
  hlt_candpath.ReadFrom(t);
  hlt_path_names_HLT.ReadFrom(t);
  hlt_p4.ReadFrom(t);
  jet_algoPF1_n.ReadFrom(t);
  jet_algoPF1_erescale.ReadFrom(t);
  jet_algoPF1_p4.ReadFrom(t);
  jet_algoPF1_beta.ReadFrom(t);
  jet_algoPF1_betaStar.ReadFrom(t);
  jet_algoPF1_betaStarClassic.ReadFrom(t);
  jet_algoPF1_dR2Mean.ReadFrom(t);
  jet_algoPF1_dRMean.ReadFrom(t);
  jet_algoPF1_dZ.ReadFrom(t);
  jet_algoPF1_frac01.ReadFrom(t);
  jet_algoPF1_frac02.ReadFrom(t);
  jet_algoPF1_frac03.ReadFrom(t);
  jet_algoPF1_frac04.ReadFrom(t);
  jet_algoPF1_frac05.ReadFrom(t);
  jet_algoPF1_full_mva.ReadFrom(t);
  jet_algoPF1_simple_mva.ReadFrom(t);
  jet_algoPF1_nCharged.ReadFrom(t);
  jet_algoPF1_nNeutrals.ReadFrom(t);
  jet_algoPF1_full_wp_level.ReadFrom(t);
  jet_algoPF1_simple_wp_level.ReadFrom(t);
  jet_algoPF1_cutbased_wp_level.ReadFrom(t);
  jet_algoPF1_pfloose.ReadFrom(t);
  jet_algoPF1_ntk.ReadFrom(t);
  jet_algoPF1_tkind.ReadFrom(t);
  jet_algoPF1_area.ReadFrom(t);
  jet_algoPF1_beta_ext.ReadFrom(t);
  jet_algoPF1_betaStar_ext.ReadFrom(t);
  jet_algoPF1_betaStarClassic_ext.ReadFrom(t);
  jet_algoPF1_full_wp_level_ext.ReadFrom(t);
  jet_algoPF1_simple_wp_level_ext.ReadFrom(t);
  jet_algoPF1_cutbased_wp_level_ext.ReadFrom(t);
  jet_algoPF1_full_mva_ext.ReadFrom(t);
  jet_algoPF1_simple_mva_ext.ReadFrom(t);
  jet_algoPF3_n.ReadFrom(t);
  jet_algoPF3_erescale.ReadFrom(t);
  jet_algoPF3_p4.ReadFrom(t);
  jet_algoPF3_beta.ReadFrom(t);
  jet_algoPF3_betaStar.ReadFrom(t);
  jet_algoPF3_betaStarClassic.ReadFrom(t);
  jet_algoPF3_dR2Mean.ReadFrom(t);
  jet_algoPF3_dRMean.ReadFrom(t);
  jet_algoPF3_dZ.ReadFrom(t);
  jet_algoPF3_frac01.ReadFrom(t);
  jet_algoPF3_frac02.ReadFrom(t);
  jet_algoPF3_frac03.ReadFrom(t);
  jet_algoPF3_frac04.ReadFrom(t);
  jet_algoPF3_frac05.ReadFrom(t);
  jet_algoPF3_full_mva.ReadFrom(t);
  jet_algoPF3_simple_mva.ReadFrom(t);
  jet_algoPF3_nCharged.ReadFrom(t);
  jet_algoPF3_nNeutrals.ReadFrom(t);
  jet_algoPF3_full_wp_level.ReadFrom(t);
  jet_algoPF3_simple_wp_level.ReadFrom(t);
  jet_algoPF3_cutbased_wp_level.ReadFrom(t);
  jet_algoPF3_pfloose.ReadFrom(t);
  jet_algoPF3_ntk.ReadFrom(t);
  jet_algoPF3_tkind.ReadFrom(t);
  jet_algoPF3_area.ReadFrom(t);
  jet_algoPF3_beta_ext.ReadFrom(t);
  jet_algoPF3_betaStar_ext.ReadFrom(t);
  jet_algoPF3_betaStarClassic_ext.ReadFrom(t);
  jet_algoPF3_full_wp_level_ext.ReadFrom(t);
  jet_algoPF3_simple_wp_level_ext.ReadFrom(t);
  jet_algoPF3_cutbased_wp_level_ext.ReadFrom(t);
  jet_algoPF3_full_mva_ext.ReadFrom(t);
  jet_algoPF3_simple_mva_ext.ReadFrom(t);
  pho_pfRawEnergy.ReadFrom(t);
  pho_pfe2x2.ReadFrom(t);
  pho_pfe3x3.ReadFrom(t);
  pho_pfe5x5.ReadFrom(t);
  pho_pfsieie.ReadFrom(t);
  pho_pfsieip.ReadFrom(t);
  pho_pfsipip.ReadFrom(t);
  pho_pfemaxxtal.ReadFrom(t);
  pho_pfe2nd.ReadFrom(t);
  vtx_std_mva.ReadFrom(t);
  vtx_std_vertexz.ReadFrom(t);
  vtx_std_nconv.ReadFrom(t);
  vtx_std_nlegs.ReadFrom(t);
  vtx_std_pulltoconv.ReadFrom(t);
  vtx_std_limpulltoconv.ReadFrom(t);
  vtx_std_diphopt.ReadFrom(t);
  vtx_std_diphopx.ReadFrom(t);
  vtx_std_diphopy.ReadFrom(t);
  vtx_std_nch.ReadFrom(t);
  vtx_std_ptmax.ReadFrom(t);
  vtx_std_sumpt.ReadFrom(t);
  vtx_std_ptvtx.ReadFrom(t);
  vtx_std_pxvtx.ReadFrom(t);
  vtx_std_pyvtx.ReadFrom(t);
  vtx_std_acosA.ReadFrom(t);
  vtx_std_ptasym.ReadFrom(t);
  vtx_std_ptbal.ReadFrom(t);
  vtx_std_nchthr.ReadFrom(t);
  vtx_std_ptmax3.ReadFrom(t);
  vtx_std_thrust.ReadFrom(t);
  vtx_std_sumweight.ReadFrom(t);
  vtx_std_sumpt2.ReadFrom(t);
  vtx_std_ptratio.ReadFrom(t);
  vtx_std_pzasym.ReadFrom(t);
  vtx_std_spher.ReadFrom(t);
  vtx_std_aplan.ReadFrom(t);
  vtx_std_sumpr.ReadFrom(t);
  vtx_std_sumawy.ReadFrom(t);
  vtx_std_sumtrv.ReadFrom(t);
  vtx_std_sumtwd.ReadFrom(t);
  vtx_std_awytwdasym.ReadFrom(t);
  vtx_std_pho1.ReadFrom(t);
  vtx_std_pho2.ReadFrom(t);
  pho_matchingConv.ReadFrom(t);
  vtx_std_evt_mva.ReadFrom(t);
  vtx_std_ranked_list.ReadFrom(t);
  vtx_std_sel.ReadFrom(t);
  pho_tkiso_recvtx_030_002_0000_10_01.ReadFrom(t);
  pho_tkiso_badvtx_040_002_0000_10_01.ReadFrom(t);
  pho_tkiso_badvtx_id.ReadFrom(t);
  pho_pfiso_charged_badvtx_04.ReadFrom(t);
  pho_pfiso_charged_badvtx_id.ReadFrom(t);
  pho_ZeeVal_tkiso_recvtx_030_002_0000_10_01.ReadFrom(t);
  pho_ZeeVal_tkiso_badvtx_040_002_0000_10_01.ReadFrom(t);
  pho_ZeeVal_tkiso_badvtx_id.ReadFrom(t);
  pho_mitmva.ReadFrom(t);
  pho_drtotk_25_99.ReadFrom(t);
  dipho_n.ReadFrom(t);
  dipho_leadind.ReadFrom(t);
  dipho_subleadind.ReadFrom(t);
  dipho_vtxind.ReadFrom(t);
  dipho_sumpt.ReadFrom(t);
  pho_cic6cutlevel_lead.ReadFrom(t);
  pho_cic6passcuts_lead.ReadFrom(t);
  pho_cic6cutlevel_sublead.ReadFrom(t);
  pho_cic6passcuts_sublead.ReadFrom(t);
  pho_cic4cutlevel_lead.ReadFrom(t);
  pho_cic4passcuts_lead.ReadFrom(t);
  pho_cic4cutlevel_sublead.ReadFrom(t);
  pho_cic4passcuts_sublead.ReadFrom(t);
  pho_cic4pfcutlevel_lead.ReadFrom(t);
  pho_cic4pfpasscuts_lead.ReadFrom(t);
  pho_cic4pfcutlevel_sublead.ReadFrom(t);
  pho_cic4pfpasscuts_sublead.ReadFrom(t);
  pho_genmatched.ReadFrom(t);
  pho_regr_energy_otf.ReadFrom(t);
  pho_regr_energyerr_otf.ReadFrom(t);
  jet_algoPF1_genMatched.ReadFrom(t);
  jet_algoPF1_vbfMatched.ReadFrom(t);
  jet_algoPF1_genPt.ReadFrom(t);
  jet_algoPF1_genDr.ReadFrom(t);
  jet_algoPF3_genMatched.ReadFrom(t);
  jet_algoPF3_vbfMatched.ReadFrom(t);
  jet_algoPF3_genPt.ReadFrom(t);
  jet_algoPF3_genDr.ReadFrom(t);
  shiftMET_pt.ReadFrom(t);
  shiftMET_phi.ReadFrom(t);
  smearMET_pt.ReadFrom(t);
  smearMET_phi.ReadFrom(t);
  shiftsmearMET_pt.ReadFrom(t);
  shiftsmearMET_phi.ReadFrom(t);
  shiftscaleMET_pt.ReadFrom(t);
  shiftscaleMET_phi.ReadFrom(t);
  shiftMET_eta.ReadFrom(t);
  shiftMET_e.ReadFrom(t);
  shiftscaleMET_eta.ReadFrom(t);
  shiftscaleMET_e.ReadFrom(t);
  gh_gen2reco1.ReadFrom(t);
  gh_gen2reco2.ReadFrom(t);
  gh_vbfq1_pdgid.ReadFrom(t);
  gh_vbfq2_pdgid.ReadFrom(t);
  gh_vh_pdgid.ReadFrom(t);
  gh_vh1_pdgid.ReadFrom(t);
  gh_vh2_pdgid.ReadFrom(t);
  gh_higgs_p4.ReadFrom(t);
  gh_pho1_p4.ReadFrom(t);
  gh_pho2_p4.ReadFrom(t);
  gh_vbfq1_p4.ReadFrom(t);
  gh_vbfq2_p4.ReadFrom(t);
  gh_vh1_p4.ReadFrom(t);
  gh_vh2_p4.ReadFrom(t);

}
