#include <TClonesArray.h>
#include <TTree.h>
#include "SharedHandle.h"
#include <vector>

using namespace std;

Long64_t m_entry_number;

SharedHandle<Int_t> event("event", &m_entry_number);
SharedHandle<Int_t> lumis("lumis", &m_entry_number);
SharedHandle<Int_t> run("run", &m_entry_number);
SharedHandle<Int_t> bx("bx", &m_entry_number);
SharedHandle<Int_t> jet_algo1_n("jet_algo1_n", &m_entry_number);
SharedHandle<TClonesArray*> jet_algo1_p4("jet_algo1_p4", &m_entry_number);
SharedHandle<Int_t*> jet_algo1_ntk("jet_algo1_ntk", &m_entry_number, 200);
SharedHandle<vector<vector<unsigned short> >*> jet_algo1_tkind("jet_algo1_tkind", &m_entry_number);
SharedHandle<Int_t> jet_algo2_n("jet_algo2_n", &m_entry_number);
SharedHandle<TClonesArray*> jet_algo2_p4("jet_algo2_p4", &m_entry_number);
SharedHandle<Int_t*> jet_algo2_ntk("jet_algo2_ntk", &m_entry_number, 200);
SharedHandle<vector<vector<unsigned short> >*> jet_algo2_tkind("jet_algo2_tkind", &m_entry_number);
SharedHandle<Int_t> tk_n("tk_n", &m_entry_number);
SharedHandle<TClonesArray*> tk_p4("tk_p4", &m_entry_number);
SharedHandle<TClonesArray*> tk_vtx_pos("tk_vtx_pos", &m_entry_number);
SharedHandle<Int_t*> tk_nhits("tk_nhits", &m_entry_number, 1500);
SharedHandle<Int_t*> tk_nlosthit("tk_nlosthit", &m_entry_number, 1500);
SharedHandle<Int_t*> tk_quality("tk_quality", &m_entry_number, 1500);
SharedHandle<TClonesArray*> sc_p4("sc_p4", &m_entry_number);
SharedHandle<TClonesArray*> sc_xyz("sc_xyz", &m_entry_number);
SharedHandle<Int_t> pho_n("pho_n", &m_entry_number);
SharedHandle<Float_t*> pho_crackcorr("pho_crackcorr", &m_entry_number, 100);
SharedHandle<Float_t*> pho_localcorr("pho_localcorr", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEB("pho_isEB", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEE("pho_isEE", &m_entry_number, 100);
SharedHandle<Float_t*> pho_see("pho_see", &m_entry_number, 100);
SharedHandle<Float_t*> pho_sieie("pho_sieie", &m_entry_number, 100);
SharedHandle<Float_t*> pho_sipip("pho_sipip", &m_entry_number, 100);
SharedHandle<Float_t*> pho_sieip("pho_sieip", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e1x5("pho_e1x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5("pho_e2x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e3x3("pho_e3x3", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e5x5("pho_e5x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_emaxxtal("pho_emaxxtal", &m_entry_number, 100);
SharedHandle<Float_t*> pho_hoe("pho_hoe", &m_entry_number, 100);
SharedHandle<Float_t*> pho_r1x5("pho_r1x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_r2x5("pho_r2x5", &m_entry_number, 100);
SharedHandle<Float_t*> pho_r9("pho_r9", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEBGap("pho_isEBGap", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEEGap("pho_isEEGap", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isEBEEGap("pho_isEBEEGap", &m_entry_number, 100);
SharedHandle<Float_t*> pho_zernike20("pho_zernike20", &m_entry_number, 100);
SharedHandle<Float_t*> pho_zernike42("pho_zernike42", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2nd("pho_e2nd", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5right("pho_e2x5right", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5left("pho_e2x5left", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5Top("pho_e2x5Top", &m_entry_number, 100);
SharedHandle<Float_t*> pho_e2x5bottom("pho_e2x5bottom", &m_entry_number, 100);
SharedHandle<Float_t*> pho_eright("pho_eright", &m_entry_number, 100);
SharedHandle<Float_t*> pho_eleft("pho_eleft", &m_entry_number, 100);
SharedHandle<Float_t*> pho_etop("pho_etop", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ebottom("pho_ebottom", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_time("pho_seed_time", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_outoftimechi2("pho_seed_outoftimechi2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_chi2("pho_seed_chi2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_recoflag("pho_seed_recoflag", &m_entry_number, 100);
SharedHandle<Float_t*> pho_seed_severity("pho_seed_severity", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ecalsumetconedr04("pho_ecalsumetconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_hcalsumetconedr04("pho_hcalsumetconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_trksumptsolidconedr04("pho_trksumptsolidconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_trksumpthollowconedr04("pho_trksumpthollowconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ntrksolidconedr04("pho_ntrksolidconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ntrkhollowconedr04("pho_ntrkhollowconedr04", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ecalsumetconedr03("pho_ecalsumetconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_hcalsumetconedr03("pho_hcalsumetconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_trksumptsolidconedr03("pho_trksumptsolidconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_trksumpthollowconedr03("pho_trksumpthollowconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ntrksolidconedr03("pho_ntrksolidconedr03", &m_entry_number, 100);
SharedHandle<Float_t*> pho_ntrkhollowconedr03("pho_ntrkhollowconedr03", &m_entry_number, 100);
SharedHandle<Int_t*> pho_barrel("pho_barrel", &m_entry_number, 100);
SharedHandle<Int_t*> pho_haspixseed("pho_haspixseed", &m_entry_number, 100);
SharedHandle<Int_t*> pho_hasconvtks("pho_hasconvtks", &m_entry_number, 100);
SharedHandle<Int_t*> pho_nconv("pho_nconv", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_ntracks("pho_conv_ntracks", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_pairinvmass("pho_conv_pairinvmass", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_paircotthetasep("pho_conv_paircotthetasep", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_eoverp("pho_conv_eoverp", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_zofprimvtxfromtrks("pho_conv_zofprimvtxfromtrks", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_distofminapproach("pho_conv_distofminapproach", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_dphitrksatvtx("pho_conv_dphitrksatvtx", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_dphitrksatecal("pho_conv_dphitrksatecal", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_detatrksatecal("pho_conv_detatrksatecal", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_d0("pho_conv_tk1_d0", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_pout("pho_conv_tk1_pout", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_pin("pho_conv_tk1_pin", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_d0("pho_conv_tk2_d0", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_pout("pho_conv_tk2_pout", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_pin("pho_conv_tk2_pin", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_dz("pho_conv_tk1_dz", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk1_dzerr("pho_conv_tk1_dzerr", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_tk1_nh("pho_conv_tk1_nh", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_dz("pho_conv_tk2_dz", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_tk2_dzerr("pho_conv_tk2_dzerr", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_tk2_nh("pho_conv_tk2_nh", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_ch1ch2("pho_conv_ch1ch2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_chi2("pho_conv_chi2", &m_entry_number, 100);
SharedHandle<Float_t*> pho_conv_chi2_probability("pho_conv_chi2_probability", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_validvtx("pho_conv_validvtx", &m_entry_number, 100);
SharedHandle<Int_t*> pho_conv_MVALikelihood("pho_conv_MVALikelihood", &m_entry_number, 100);
SharedHandle<TClonesArray*> pho_p4("pho_p4", &m_entry_number);
SharedHandle<TClonesArray*> pho_calopos("pho_calopos", &m_entry_number);
SharedHandle<TClonesArray*> pho_conv_vtx("pho_conv_vtx", &m_entry_number);
SharedHandle<TClonesArray*> pho_conv_pair_momentum("pho_conv_pair_momentum", &m_entry_number);
SharedHandle<TClonesArray*> pho_conv_refitted_momentum("pho_conv_refitted_momentum", &m_entry_number);
SharedHandle<TClonesArray*> pho_conv_vertexcorrected_p4("pho_conv_vertexcorrected_p4", &m_entry_number);
SharedHandle<Int_t*> pho_scind("pho_scind", &m_entry_number, 100);
SharedHandle<Float_t*> pho_residCorrEnergy("pho_residCorrEnergy", &m_entry_number, 100);
SharedHandle<Float_t*> pho_residCorrResn("pho_residCorrResn", &m_entry_number, 100);
SharedHandle<Int_t*> pho_isconv("pho_isconv", &m_entry_number, 100);
SharedHandle<Int_t> conv_n("conv_n", &m_entry_number);
SharedHandle<TClonesArray*> conv_p4("conv_p4", &m_entry_number);
SharedHandle<Int_t*> conv_ntracks("conv_ntracks", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_pairinvmass("conv_pairinvmass", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_paircotthetasep("conv_paircotthetasep", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_eoverp("conv_eoverp", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_distofminapproach("conv_distofminapproach", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_dphitrksatvtx("conv_dphitrksatvtx", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_dphitrksatecal("conv_dphitrksatecal", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_detatrksatecal("conv_detatrksatecal", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_dxy("conv_dxy", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_dz("conv_dz", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_lxy("conv_lxy", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_lz("conv_lz", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_zofprimvtxfromtrks("conv_zofprimvtxfromtrks", &m_entry_number, 2000);
SharedHandle<vector<vector<unsigned short> >*> conv_nHitsBeforeVtx("conv_nHitsBeforeVtx", &m_entry_number);
SharedHandle<Int_t*> conv_nSharedHits("conv_nSharedHits", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_validvtx("conv_validvtx", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_MVALikelihood("conv_MVALikelihood", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_chi2("conv_chi2", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_chi2_probability("conv_chi2_probability", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_vtx_xErr("conv_vtx_xErr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_vtx_yErr("conv_vtx_yErr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_vtx_zErr("conv_vtx_zErr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_dz("conv_tk1_dz", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_dz("conv_tk2_dz", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_dzerr("conv_tk1_dzerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_dzerr("conv_tk2_dzerr", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_tk1_nh("conv_tk1_nh", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_tk2_nh("conv_tk2_nh", &m_entry_number, 2000);
SharedHandle<Int_t*> conv_ch1ch2("conv_ch1ch2", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_d0("conv_tk1_d0", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_pout("conv_tk1_pout", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_pin("conv_tk1_pin", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_d0("conv_tk2_d0", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_pout("conv_tk2_pout", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_pin("conv_tk2_pin", &m_entry_number, 2000);
SharedHandle<TClonesArray*> conv_vtx("conv_vtx", &m_entry_number);
SharedHandle<Float_t*> conv_tk1_pterr("conv_tk1_pterr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_pterr("conv_tk2_pterr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_etaerr("conv_tk1_etaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_etaerr("conv_tk2_etaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_thetaerr("conv_tk1_thetaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_thetaerr("conv_tk2_thetaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_phierr("conv_tk1_phierr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_phierr("conv_tk2_phierr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk1_lambdaerr("conv_tk1_lambdaerr", &m_entry_number, 2000);
SharedHandle<Float_t*> conv_tk2_lambdaerr("conv_tk2_lambdaerr", &m_entry_number, 2000);
SharedHandle<TClonesArray*> conv_pair_momentum("conv_pair_momentum", &m_entry_number);
SharedHandle<TClonesArray*> conv_refitted_momentum("conv_refitted_momentum", &m_entry_number);
SharedHandle<TClonesArray*> conv_singleleg_momentum("conv_singleleg_momentum", &m_entry_number);
SharedHandle<Int_t> process_id("process_id", &m_entry_number);
SharedHandle<Float_t> weight("weight", &m_entry_number);
SharedHandle<Float_t> pthat("pthat", &m_entry_number);
SharedHandle<Int_t> gp_n("gp_n", &m_entry_number);
SharedHandle<TClonesArray*> gp_p4("gp_p4", &m_entry_number);
SharedHandle<TClonesArray*> gp_vtx("gp_vtx", &m_entry_number);
SharedHandle<Short_t*> gp_status("gp_status", &m_entry_number, 10000);
SharedHandle<Short_t*> gp_pdgid("gp_pdgid", &m_entry_number, 10000);
SharedHandle<Short_t*> gp_mother("gp_mother", &m_entry_number, 10000);
SharedHandle<Int_t> gv_n("gv_n", &m_entry_number);
SharedHandle<TClonesArray*> gv_pos("gv_pos", &m_entry_number);
SharedHandle<Int_t> pu_n("pu_n", &m_entry_number);
SharedHandle<vector<float>*> pu_zpos("pu_zpos", &m_entry_number);
SharedHandle<vector<float>*> pu_sumpt_lowpt("pu_sumpt_lowpt", &m_entry_number);
SharedHandle<vector<float>*> pu_sumpt_highpt("pu_sumpt_highpt", &m_entry_number);
SharedHandle<vector<int>*> pu_ntrks_lowpt("pu_ntrks_lowpt", &m_entry_number);
SharedHandle<vector<int>*> pu_ntrks_highpt("pu_ntrks_highpt", &m_entry_number);
SharedHandle<Int_t> vtx_std_n("vtx_std_n", &m_entry_number);
SharedHandle<Int_t*> vtx_std_ntks("vtx_std_ntks", &m_entry_number, 100);
SharedHandle<Float_t*> vtx_std_x2dof("vtx_std_x2dof", &m_entry_number, 100);
SharedHandle<TClonesArray*> vtx_std_xyz("vtx_std_xyz", &m_entry_number);
SharedHandle<TClonesArray*> vtx_std_dxdydz("vtx_std_dxdydz", &m_entry_number);
SharedHandle<Float_t*> vtx_std_ndof("vtx_std_ndof", &m_entry_number, 100);
SharedHandle<Float_t> rho_algo1("rho_algo1", &m_entry_number);
SharedHandle<TClonesArray*> bs_xyz("bs_xyz", &m_entry_number);
SharedHandle<Float_t> bs_sigmaZ("bs_sigmaZ", &m_entry_number);
SharedHandle<Float_t> bs_x0Error("bs_x0Error", &m_entry_number);
SharedHandle<Float_t> bs_y0Error("bs_y0Error", &m_entry_number);
SharedHandle<Float_t> bs_z0Error("bs_z0Error", &m_entry_number);
SharedHandle<Float_t> bs_sigmaZ0Error("bs_sigmaZ0Error", &m_entry_number);
SharedHandle<Float_t> met_tcmet("met_tcmet", &m_entry_number);
SharedHandle<Float_t> met_phi_tcmet("met_phi_tcmet", &m_entry_number);
SharedHandle<vector<unsigned short>*> hlt1_bit("hlt1_bit", &m_entry_number);
SharedHandle<Int_t> hlt_n("hlt_n", &m_entry_number);
SharedHandle<vector<vector<unsigned short> >*> hlt_candpath("hlt_candpath", &m_entry_number);
SharedHandle<vector<string>*> hlt_path_names_HLT1("hlt_path_names_HLT1", &m_entry_number);
SharedHandle<TClonesArray*> hlt_p4("hlt_p4", &m_entry_number);
SharedHandle<Int_t> l1emiso_n("l1emiso_n", &m_entry_number);
SharedHandle<Float_t*> l1emiso_et("l1emiso_et", &m_entry_number, 10);
SharedHandle<Float_t*> l1emiso_eta("l1emiso_eta", &m_entry_number, 10);
SharedHandle<Float_t*> l1emiso_phi("l1emiso_phi", &m_entry_number, 10);
SharedHandle<Int_t> l1emnoniso_n("l1emnoniso_n", &m_entry_number);
SharedHandle<Float_t*> l1emnoniso_et("l1emnoniso_et", &m_entry_number, 10);
SharedHandle<Float_t*> l1emnoniso_eta("l1emnoniso_eta", &m_entry_number, 10);
SharedHandle<Float_t*> l1emnoniso_phi("l1emnoniso_phi", &m_entry_number, 10);
SharedHandle<vector<int>*> l1bits_phy("l1bits_phy", &m_entry_number);
SharedHandle<Int_t> l1_labels_("l1_labels_", &m_entry_number);
SharedHandle<string*> l1_labels_first("l1_labels_first", &m_entry_number, 100);
SharedHandle<Int_t*> l1_labels_second("l1_labels_second", &m_entry_number, 100);
SharedHandle<Int_t> jet_algoPF1_n("jet_algoPF1_n", &m_entry_number);
SharedHandle<Float_t*> jet_algoPF1_erescale("jet_algoPF1_erescale", &m_entry_number, 200);
SharedHandle<vector<vector<float> >*> vtx_std_mva("vtx_std_mva", &m_entry_number);
SharedHandle<vector<float>*> vtx_std_vertexz("vtx_std_vertexz", &m_entry_number);
SharedHandle<vector<float>*> vtx_std_nconv("vtx_std_nconv", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_pulltoconv("vtx_std_pulltoconv", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_limpulltoconv("vtx_std_limpulltoconv", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_diphopt("vtx_std_diphopt", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_nch("vtx_std_nch", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptmax("vtx_std_ptmax", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumpt("vtx_std_sumpt", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptvtx("vtx_std_ptvtx", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_acosA("vtx_std_acosA", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptasym("vtx_std_ptasym", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptbal("vtx_std_ptbal", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_nchthr("vtx_std_nchthr", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptmax3("vtx_std_ptmax3", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_thrust("vtx_std_thrust", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumweight("vtx_std_sumweight", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumpt2("vtx_std_sumpt2", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_ptratio("vtx_std_ptratio", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_pzasym("vtx_std_pzasym", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_spher("vtx_std_spher", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_aplan("vtx_std_aplan", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumpr("vtx_std_sumpr", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumawy("vtx_std_sumawy", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumtrv("vtx_std_sumtrv", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_sumtwd("vtx_std_sumtwd", &m_entry_number);
SharedHandle<vector<vector<float> >*> vtx_std_awytwdasym("vtx_std_awytwdasym", &m_entry_number);
SharedHandle<Int_t> vtx_std_pho1("vtx_std_pho1", &m_entry_number);
SharedHandle<Int_t> vtx_std_pho2("vtx_std_pho2", &m_entry_number);
SharedHandle<vector<int>*> pho_matchingConv("pho_matchingConv", &m_entry_number);
SharedHandle<vector<float>*> vtx_std_evt_mva("vtx_std_evt_mva", &m_entry_number);
SharedHandle<vector<vector<int> >*> vtx_std_ranked_list("vtx_std_ranked_list", &m_entry_number);
SharedHandle<Int_t> vtx_std_sel("vtx_std_sel", &m_entry_number);
SharedHandle<vector<vector<float> >*> pho_tkiso_recvtx_030_002_0000_10_01("pho_tkiso_recvtx_030_002_0000_10_01", &m_entry_number);
SharedHandle<Float_t*> pho_tkiso_badvtx_040_002_0000_10_01("pho_tkiso_badvtx_040_002_0000_10_01", &m_entry_number, 100);
SharedHandle<Int_t*> pho_tkiso_badvtx_id("pho_tkiso_badvtx_id", &m_entry_number, 100);
SharedHandle<Float_t*> pho_drtotk_25_99("pho_drtotk_25_99", &m_entry_number, 100);
SharedHandle<Int_t> dipho_n("dipho_n", &m_entry_number);
SharedHandle<Int_t*> dipho_leadind("dipho_leadind", &m_entry_number, 100);
SharedHandle<Int_t*> dipho_subleadind("dipho_subleadind", &m_entry_number, 100);
SharedHandle<Int_t*> dipho_vtxind("dipho_vtxind", &m_entry_number, 100);
SharedHandle<Float_t*> dipho_sumpt("dipho_sumpt", &m_entry_number, 100);
SharedHandle<vector<vector<short> >*> pho_cic6cutlevel_lead("pho_cic6cutlevel_lead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic6passcuts_lead("pho_cic6passcuts_lead", &m_entry_number);
SharedHandle<vector<vector<short> >*> pho_cic6cutlevel_sublead("pho_cic6cutlevel_sublead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic6passcuts_sublead("pho_cic6passcuts_sublead", &m_entry_number);
SharedHandle<vector<vector<short> >*> pho_cic4cutlevel_lead("pho_cic4cutlevel_lead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic4passcuts_lead("pho_cic4passcuts_lead", &m_entry_number);
SharedHandle<vector<vector<short> >*> pho_cic4cutlevel_sublead("pho_cic4cutlevel_sublead", &m_entry_number);
SharedHandle<vector<vector<vector<unsigned int> > >*> pho_cic4passcuts_sublead("pho_cic4passcuts_sublead", &m_entry_number);

void connect_variables(TTree* t){

  event.ReadFrom(t);
  lumis.ReadFrom(t);
  run.ReadFrom(t);
  bx.ReadFrom(t);
  jet_algo1_n.ReadFrom(t);
  jet_algo1_p4.ReadFrom(t);
  jet_algo1_ntk.ReadFrom(t);
  jet_algo1_tkind.ReadFrom(t);
  jet_algo2_n.ReadFrom(t);
  jet_algo2_p4.ReadFrom(t);
  jet_algo2_ntk.ReadFrom(t);
  jet_algo2_tkind.ReadFrom(t);
  tk_n.ReadFrom(t);
  tk_p4.ReadFrom(t);
  tk_vtx_pos.ReadFrom(t);
  tk_nhits.ReadFrom(t);
  tk_nlosthit.ReadFrom(t);
  tk_quality.ReadFrom(t);
  sc_p4.ReadFrom(t);
  sc_xyz.ReadFrom(t);
  pho_n.ReadFrom(t);
  pho_crackcorr.ReadFrom(t);
  pho_localcorr.ReadFrom(t);
  pho_isEB.ReadFrom(t);
  pho_isEE.ReadFrom(t);
  pho_see.ReadFrom(t);
  pho_sieie.ReadFrom(t);
  pho_sipip.ReadFrom(t);
  pho_sieip.ReadFrom(t);
  pho_e1x5.ReadFrom(t);
  pho_e2x5.ReadFrom(t);
  pho_e3x3.ReadFrom(t);
  pho_e5x5.ReadFrom(t);
  pho_emaxxtal.ReadFrom(t);
  pho_hoe.ReadFrom(t);
  pho_r1x5.ReadFrom(t);
  pho_r2x5.ReadFrom(t);
  pho_r9.ReadFrom(t);
  pho_isEBGap.ReadFrom(t);
  pho_isEEGap.ReadFrom(t);
  pho_isEBEEGap.ReadFrom(t);
  pho_zernike20.ReadFrom(t);
  pho_zernike42.ReadFrom(t);
  pho_e2nd.ReadFrom(t);
  pho_e2x5right.ReadFrom(t);
  pho_e2x5left.ReadFrom(t);
  pho_e2x5Top.ReadFrom(t);
  pho_e2x5bottom.ReadFrom(t);
  pho_eright.ReadFrom(t);
  pho_eleft.ReadFrom(t);
  pho_etop.ReadFrom(t);
  pho_ebottom.ReadFrom(t);
  pho_seed_time.ReadFrom(t);
  pho_seed_outoftimechi2.ReadFrom(t);
  pho_seed_chi2.ReadFrom(t);
  pho_seed_recoflag.ReadFrom(t);
  pho_seed_severity.ReadFrom(t);
  pho_ecalsumetconedr04.ReadFrom(t);
  pho_hcalsumetconedr04.ReadFrom(t);
  pho_trksumptsolidconedr04.ReadFrom(t);
  pho_trksumpthollowconedr04.ReadFrom(t);
  pho_ntrksolidconedr04.ReadFrom(t);
  pho_ntrkhollowconedr04.ReadFrom(t);
  pho_ecalsumetconedr03.ReadFrom(t);
  pho_hcalsumetconedr03.ReadFrom(t);
  pho_trksumptsolidconedr03.ReadFrom(t);
  pho_trksumpthollowconedr03.ReadFrom(t);
  pho_ntrksolidconedr03.ReadFrom(t);
  pho_ntrkhollowconedr03.ReadFrom(t);
  pho_barrel.ReadFrom(t);
  pho_haspixseed.ReadFrom(t);
  pho_hasconvtks.ReadFrom(t);
  pho_nconv.ReadFrom(t);
  pho_conv_ntracks.ReadFrom(t);
  pho_conv_pairinvmass.ReadFrom(t);
  pho_conv_paircotthetasep.ReadFrom(t);
  pho_conv_eoverp.ReadFrom(t);
  pho_conv_zofprimvtxfromtrks.ReadFrom(t);
  pho_conv_distofminapproach.ReadFrom(t);
  pho_conv_dphitrksatvtx.ReadFrom(t);
  pho_conv_dphitrksatecal.ReadFrom(t);
  pho_conv_detatrksatecal.ReadFrom(t);
  pho_conv_tk1_d0.ReadFrom(t);
  pho_conv_tk1_pout.ReadFrom(t);
  pho_conv_tk1_pin.ReadFrom(t);
  pho_conv_tk2_d0.ReadFrom(t);
  pho_conv_tk2_pout.ReadFrom(t);
  pho_conv_tk2_pin.ReadFrom(t);
  pho_conv_tk1_dz.ReadFrom(t);
  pho_conv_tk1_dzerr.ReadFrom(t);
  pho_conv_tk1_nh.ReadFrom(t);
  pho_conv_tk2_dz.ReadFrom(t);
  pho_conv_tk2_dzerr.ReadFrom(t);
  pho_conv_tk2_nh.ReadFrom(t);
  pho_conv_ch1ch2.ReadFrom(t);
  pho_conv_chi2.ReadFrom(t);
  pho_conv_chi2_probability.ReadFrom(t);
  pho_conv_validvtx.ReadFrom(t);
  pho_conv_MVALikelihood.ReadFrom(t);
  pho_p4.ReadFrom(t);
  pho_calopos.ReadFrom(t);
  pho_conv_vtx.ReadFrom(t);
  pho_conv_pair_momentum.ReadFrom(t);
  pho_conv_refitted_momentum.ReadFrom(t);
  pho_conv_vertexcorrected_p4.ReadFrom(t);
  pho_scind.ReadFrom(t);
  pho_residCorrEnergy.ReadFrom(t);
  pho_residCorrResn.ReadFrom(t);
  pho_isconv.ReadFrom(t);
  conv_n.ReadFrom(t);
  conv_p4.ReadFrom(t);
  conv_ntracks.ReadFrom(t);
  conv_pairinvmass.ReadFrom(t);
  conv_paircotthetasep.ReadFrom(t);
  conv_eoverp.ReadFrom(t);
  conv_distofminapproach.ReadFrom(t);
  conv_dphitrksatvtx.ReadFrom(t);
  conv_dphitrksatecal.ReadFrom(t);
  conv_detatrksatecal.ReadFrom(t);
  conv_dxy.ReadFrom(t);
  conv_dz.ReadFrom(t);
  conv_lxy.ReadFrom(t);
  conv_lz.ReadFrom(t);
  conv_zofprimvtxfromtrks.ReadFrom(t);
  conv_nHitsBeforeVtx.ReadFrom(t);
  conv_nSharedHits.ReadFrom(t);
  conv_validvtx.ReadFrom(t);
  conv_MVALikelihood.ReadFrom(t);
  conv_chi2.ReadFrom(t);
  conv_chi2_probability.ReadFrom(t);
  conv_vtx_xErr.ReadFrom(t);
  conv_vtx_yErr.ReadFrom(t);
  conv_vtx_zErr.ReadFrom(t);
  conv_tk1_dz.ReadFrom(t);
  conv_tk2_dz.ReadFrom(t);
  conv_tk1_dzerr.ReadFrom(t);
  conv_tk2_dzerr.ReadFrom(t);
  conv_tk1_nh.ReadFrom(t);
  conv_tk2_nh.ReadFrom(t);
  conv_ch1ch2.ReadFrom(t);
  conv_tk1_d0.ReadFrom(t);
  conv_tk1_pout.ReadFrom(t);
  conv_tk1_pin.ReadFrom(t);
  conv_tk2_d0.ReadFrom(t);
  conv_tk2_pout.ReadFrom(t);
  conv_tk2_pin.ReadFrom(t);
  conv_vtx.ReadFrom(t);
  conv_tk1_pterr.ReadFrom(t);
  conv_tk2_pterr.ReadFrom(t);
  conv_tk1_etaerr.ReadFrom(t);
  conv_tk2_etaerr.ReadFrom(t);
  conv_tk1_thetaerr.ReadFrom(t);
  conv_tk2_thetaerr.ReadFrom(t);
  conv_tk1_phierr.ReadFrom(t);
  conv_tk2_phierr.ReadFrom(t);
  conv_tk1_lambdaerr.ReadFrom(t);
  conv_tk2_lambdaerr.ReadFrom(t);
  conv_pair_momentum.ReadFrom(t);
  conv_refitted_momentum.ReadFrom(t);
  conv_singleleg_momentum.ReadFrom(t);
  process_id.ReadFrom(t);
  weight.ReadFrom(t);
  pthat.ReadFrom(t);
  gp_n.ReadFrom(t);
  gp_p4.ReadFrom(t);
  gp_vtx.ReadFrom(t);
  gp_status.ReadFrom(t);
  gp_pdgid.ReadFrom(t);
  gp_mother.ReadFrom(t);
  gv_n.ReadFrom(t);
  gv_pos.ReadFrom(t);
  pu_n.ReadFrom(t);
  pu_zpos.ReadFrom(t);
  pu_sumpt_lowpt.ReadFrom(t);
  pu_sumpt_highpt.ReadFrom(t);
  pu_ntrks_lowpt.ReadFrom(t);
  pu_ntrks_highpt.ReadFrom(t);
  vtx_std_n.ReadFrom(t);
  vtx_std_ntks.ReadFrom(t);
  vtx_std_x2dof.ReadFrom(t);
  vtx_std_xyz.ReadFrom(t);
  vtx_std_dxdydz.ReadFrom(t);
  vtx_std_ndof.ReadFrom(t);
  rho_algo1.ReadFrom(t);
  bs_xyz.ReadFrom(t);
  bs_sigmaZ.ReadFrom(t);
  bs_x0Error.ReadFrom(t);
  bs_y0Error.ReadFrom(t);
  bs_z0Error.ReadFrom(t);
  bs_sigmaZ0Error.ReadFrom(t);
  met_tcmet.ReadFrom(t);
  met_phi_tcmet.ReadFrom(t);
  hlt1_bit.ReadFrom(t);
  hlt_n.ReadFrom(t);
  hlt_candpath.ReadFrom(t);
  hlt_path_names_HLT1.ReadFrom(t);
  hlt_p4.ReadFrom(t);
  l1emiso_n.ReadFrom(t);
  l1emiso_et.ReadFrom(t);
  l1emiso_eta.ReadFrom(t);
  l1emiso_phi.ReadFrom(t);
  l1emnoniso_n.ReadFrom(t);
  l1emnoniso_et.ReadFrom(t);
  l1emnoniso_eta.ReadFrom(t);
  l1emnoniso_phi.ReadFrom(t);
  l1bits_phy.ReadFrom(t);
  l1_labels_.ReadFrom(t);
  l1_labels_first.ReadFrom(t);
  l1_labels_second.ReadFrom(t);
  jet_algoPF1_n.ReadFrom(t);
  jet_algoPF1_erescale.ReadFrom(t);
  vtx_std_mva.ReadFrom(t);
  vtx_std_vertexz.ReadFrom(t);
  vtx_std_nconv.ReadFrom(t);
  vtx_std_pulltoconv.ReadFrom(t);
  vtx_std_limpulltoconv.ReadFrom(t);
  vtx_std_diphopt.ReadFrom(t);
  vtx_std_nch.ReadFrom(t);
  vtx_std_ptmax.ReadFrom(t);
  vtx_std_sumpt.ReadFrom(t);
  vtx_std_ptvtx.ReadFrom(t);
  vtx_std_acosA.ReadFrom(t);
  vtx_std_ptasym.ReadFrom(t);
  vtx_std_ptbal.ReadFrom(t);
  vtx_std_nchthr.ReadFrom(t);
  vtx_std_ptmax3.ReadFrom(t);
  vtx_std_thrust.ReadFrom(t);
  vtx_std_sumweight.ReadFrom(t);
  vtx_std_sumpt2.ReadFrom(t);
  vtx_std_ptratio.ReadFrom(t);
  vtx_std_pzasym.ReadFrom(t);
  vtx_std_spher.ReadFrom(t);
  vtx_std_aplan.ReadFrom(t);
  vtx_std_sumpr.ReadFrom(t);
  vtx_std_sumawy.ReadFrom(t);
  vtx_std_sumtrv.ReadFrom(t);
  vtx_std_sumtwd.ReadFrom(t);
  vtx_std_awytwdasym.ReadFrom(t);
  vtx_std_pho1.ReadFrom(t);
  vtx_std_pho2.ReadFrom(t);
  pho_matchingConv.ReadFrom(t);
  vtx_std_evt_mva.ReadFrom(t);
  vtx_std_ranked_list.ReadFrom(t);
  vtx_std_sel.ReadFrom(t);
  pho_tkiso_recvtx_030_002_0000_10_01.ReadFrom(t);
  pho_tkiso_badvtx_040_002_0000_10_01.ReadFrom(t);
  pho_tkiso_badvtx_id.ReadFrom(t);
  pho_drtotk_25_99.ReadFrom(t);
  dipho_n.ReadFrom(t);
  dipho_leadind.ReadFrom(t);
  dipho_subleadind.ReadFrom(t);
  dipho_vtxind.ReadFrom(t);
  dipho_sumpt.ReadFrom(t);
  pho_cic6cutlevel_lead.ReadFrom(t);
  pho_cic6passcuts_lead.ReadFrom(t);
  pho_cic6cutlevel_sublead.ReadFrom(t);
  pho_cic6passcuts_sublead.ReadFrom(t);
  pho_cic4cutlevel_lead.ReadFrom(t);
  pho_cic4passcuts_lead.ReadFrom(t);
  pho_cic4cutlevel_sublead.ReadFrom(t);
  pho_cic4passcuts_sublead.ReadFrom(t);

}
