# python batch_submit.py -c "OnePhoton DoubleLeg Run2012A" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/data/Photon_Run2012A-13Jul2012-v1 -s Run2012A -l Run2012A
# python batch_submit.py -c "OnePhoton DoubleLeg Run2012A" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/data/Photon_Run2012A-recover-06Aug2012-v1 -s Run2012A -l Run2012A
# python batch_submit.py -c "OnePhoton DoubleLeg Run2012B" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/data/SinglePhoton_Run2012B-13Jul2012-v1 -s Run2012B -l Run2012B
# python batch_submit.py -c "OnePhoton DoubleLeg Run2012C" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/data/SinglePhoton_Run2012C-24Aug2012-v1 -s Run2012C -l Run2012C
# python batch_submit.py -c "OnePhoton DoubleLeg Run2012C" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/data/SinglePhoton_Run2012C-PromptReco-v2 -s Run2012C -l Run2012C
# python batch_submit.py -c "OnePhoton DoubleLeg Run2012D" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/data/SinglePhoton_Run2012D-PromptReco-v1 -s Run2012D -l Run2012D

#python batch_submit.py -c "OnePhoton DoubleLeg PJet0to15" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-0to15_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets
#python batch_submit.py -c "OnePhoton DoubleLeg PJet15to30" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-15to30_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets
python batch_submit.py -c "OnePhoton DoubleLeg PJet30to50" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-30to50_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets
python batch_submit.py -c "OnePhoton DoubleLeg PJet50to80" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-50to80_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets
python batch_submit.py -c "OnePhoton DoubleLeg PJet80to120" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-80to120_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets
python batch_submit.py -c "OnePhoton DoubleLeg PJet120to170" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-120to170_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets
python batch_submit.py -c "OnePhoton DoubleLeg PJet170to300" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-170to300_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets
python batch_submit.py -c "OnePhoton DoubleLeg PJet300to470" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-300to470_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets
python batch_submit.py -c "OnePhoton DoubleLeg PJet470to800" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-470to800_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets
python batch_submit.py -c "OnePhoton DoubleLeg PJet800to1400" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/G_Pt-800to1400_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s PJets -l PJets

#python batch_submit.py -c "OnePhoton DoubleLeg QCD20to30" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/QCD_Pt_20_30_EMEnriched_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s QCD -l QCD
python batch_submit.py -c "OnePhoton DoubleLeg QCD30to80" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/QCD_Pt_30_80_EMEnriched_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s QCD -l QCD
python batch_submit.py -c "OnePhoton DoubleLeg QCD80to170" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/QCD_Pt_80_170_EMEnriched_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1_remoteGlidein -s QCD -l QCD
python batch_submit.py -c "OnePhoton DoubleLeg QCD170to250" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/QCD_Pt_170_250_EMEnriched_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s QCD -l QCD
python batch_submit.py -c "OnePhoton DoubleLeg QCD250to350" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/QCD_Pt_250_350_EMEnriched_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1_remoteGlidein -s QCD -l QCD
python batch_submit.py -c "OnePhoton DoubleLeg QCD350" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/QCD_Pt_350_EMEnriched_TuneZ2star_8TeV_pythia6_Summer12_DR53X-PU_S10_START53_V7A-v1 -s QCD -l QCD

python batch_submit.py -c "OnePhoton DoubleLeg DiPhotonJets" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/DiPhotonJets_8TeV-madgraph-tarball-v2_Summer12_DR53X-PU_S10_START53_V7A-v1 -s DiPhotonJets -l DiPhotonJets
python batch_submit.py -c "OnePhoton DoubleLeg WJets" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_Summer12_DR53X-PU_S10_START53_V7A-v2 -s WJets -l WJets
python batch_submit.py -c "OnePhoton DoubleLeg ZJets" -i /eos/cms/store/group/phys_higgs/cmshgg/reduced/PhotonPlusJet/Moriond_PJetReduction/mc/Summer12_S10_8TeV/DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball_Summer12_DR53X-PU_S10_START53_V7A-v1 -s ZJets -l ZJets
